package tsgrammar

// Code generated by vendor.sh — DO NOT EDIT.
// Grammar: tree-sitter-grammars/tree-sitter-objc @ v3.0.2 (src)

// #cgo CFLAGS: -std=c11 -fPIC -I${SRCDIR}
// typedef struct TSLanguage TSLanguage;
// const TSLanguage *tree_sitter_objc(void);
import "C"
import "unsafe"

// Language returns the C TSLanguage pointer for objc.
func Language() unsafe.Pointer { return unsafe.Pointer(C.tree_sitter_objc()) }
