package main

import (
	"bufio"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// The launcher keeps server configuration in ~/.cix/server.env, deliberately
// NOT in the repo-root .env that install-server.sh uses. A developer checkout
// and an installed .app can then coexist on one machine without fighting over
// one file — which matters because they also share a launchd label.
//
// The file is the single source of truth for the server process: the launchd
// plist carries no configuration, the wrapper script just sources this file.
// Editing it and restarting is enough, with no plist regeneration.

const (
	defaultServerPort = 21847
	envFileMode       = 0o600
)

func cixHome() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".cix"), nil
}

func serverEnvPath() (string, error) {
	dir, err := cixHome()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "server.env"), nil
}

// readServerEnv parses ~/.cix/server.env into a map.
//
// The parser is deliberately small: this file is written by us and consumed by
// our own wrapper (`set -a; source`), so it never has to cope with the full
// range of shell syntax. It does strip matching quotes, because the writer adds
// them.
func readServerEnv() (map[string]string, error) {
	path, err := serverEnvPath()
	if err != nil {
		return nil, err
	}
	return readEnvFile(path)
}

// readEnvFile parses any KEY=value file in the same dialect. Used for our own
// server.env and, during a takeover, for the .env an install-server.sh wrapper
// sources — which is written by a different tool and may quote differently.
func readEnvFile(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	vars := map[string]string{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		key = strings.TrimSpace(strings.TrimPrefix(key, "export "))
		value = strings.TrimSpace(value)
		if len(value) >= 2 {
			if (value[0] == '\'' && value[len(value)-1] == '\'') ||
				(value[0] == '"' && value[len(value)-1] == '"') {
				value = value[1 : len(value)-1]
			}
		}
		// Undo the writer's escaping of an embedded single quote.
		vars[key] = strings.ReplaceAll(value, `'\''`, `'`)
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	return vars, nil
}

// writeServerEnv writes the file at 0600 — it holds an API key and a bootstrap
// password. Written via a temp file + rename so a crash mid-write cannot leave
// the server with a half-parsed configuration.
func writeServerEnv(vars map[string]string) error {
	path, err := serverEnvPath()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}

	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("# Generated by cix.app. Sourced by ~/.cix/launchd/run-cix-server.sh.\n")
	sb.WriteString("# Contains an API key and the bootstrap password: keep at mode 0600.\n")
	for _, k := range keys {
		fmt.Fprintf(&sb, "%s='%s'\n", k, strings.ReplaceAll(vars[k], `'`, `'\''`))
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(sb.String()), envFileMode); err != nil {
		return err
	}
	// WriteFile honours the mode only when it creates the file; an existing
	// temp file from a previous crash would keep its old mode.
	if err := os.Chmod(tmp, envFileMode); err != nil {
		os.Remove(tmp)
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp)
		return err
	}
	return nil
}

// serverPort returns the port the server is configured to listen on.
func serverPort(vars map[string]string) int {
	if raw, ok := vars["CIX_PORT"]; ok {
		if n, err := strconv.Atoi(strings.TrimSpace(raw)); err == nil && n > 0 && n < 65536 {
			return n
		}
	}
	return defaultServerPort
}

// Bind addresses the network toggle switches between.
//
// The server's own default is an empty CIX_BIND_ADDR, meaning every interface —
// that is what containers need and every existing deployment already has, so it
// stays. A desktop install is a different situation: the app writes loopback at
// first run, because "everyone on the café Wi-Fi can query my code index" is
// rarely what someone installing a menu bar app had in mind.
const (
	bindLocalOnly     = "127.0.0.1"
	bindAllInterfaces = "0.0.0.0"
)

// isLocalOnly reports whether the configured bind address is loopback.
//
// An absent CIX_BIND_ADDR is NOT local-only: it is the server's all-interfaces
// default. Reading it the other way would show a reassuring "local only" on
// exactly the installs that are exposed.
func isLocalOnly(vars map[string]string) bool {
	addr := strings.TrimSpace(vars["CIX_BIND_ADDR"])
	if addr == "" {
		return false
	}
	if ip := net.ParseIP(addr); ip != nil {
		return ip.IsLoopback()
	}
	return strings.EqualFold(addr, "localhost")
}

// dashboardURL is built from the server.env port, never from the CLI config.
// The CLI's default server may legitimately point at a remote cix — opening
// that in a browser when the user clicked "Open Dashboard" on a local menu bar
// item would be wrong, and confusing in exactly the case where the local server
// is down.
func dashboardURL(vars map[string]string) string {
	return fmt.Sprintf("http://localhost:%d/dashboard", serverPort(vars))
}

func localBaseURL(vars map[string]string) string {
	return fmt.Sprintf("http://localhost:%d", serverPort(vars))
}

// setDefault fills a key only when it has no value yet, so re-running setup
// keeps whatever the user has chosen since the first time.
func setDefault(vars map[string]string, key, value string) {
	if strings.TrimSpace(vars[key]) == "" {
		vars[key] = value
	}
}
