package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// launchd control for the cix-server agent.
//
// The label, paths and helper semantics deliberately match install-server.sh
// (:43-47, :211-270) so a machine never ends up with two competing definitions
// of "the cix server agent". The one divergence is KeepAlive — see writePlist.
//
// The hard-won rule from the installer, which applies verbatim here: no
// launchctl exit code is worth trusting. `bootout` returns while the job is
// still draining out of the domain, and the legacy `load` exits 0 even when it
// failed. Every step asks launchd whether the label is really there.

const (
	launchdLabel = "com.cix.server"

	// Provenance marker written into the wrapper script. Its absence is how we
	// recognise a wrapper generated by install-server.sh — same label, but
	// pointing at a repo checkout rather than at this bundle.
	managedByMarker = "# managed-by: cix.app"
)

func launchdDomain() string { return fmt.Sprintf("gui/%d", os.Getuid()) }

func launchdTarget() string { return launchdDomain() + "/" + launchdLabel }

func plistPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, "Library", "LaunchAgents", launchdLabel+".plist"), nil
}

func wrapperPath() (string, error) {
	dir, err := cixHome()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "launchd", "run-cix-server.sh"), nil
}

func logDir() (string, error) {
	dir, err := cixHome()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "logs"), nil
}

// runLaunchctl runs one launchctl subcommand with a deadline. launchctl is
// normally instantaneous, so the timeout is a guard against a wedged domain
// rather than an expected wait.
func runLaunchctl(args ...string) (string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	out, err := exec.CommandContext(ctx, "launchctl", args...).CombinedOutput()
	return string(out), err
}

// launchdLoaded reports whether the agent is present in the user domain.
// `launchctl print` is the only trustworthy check available.
func launchdLoaded() bool {
	_, err := runLaunchctl("print", launchdTarget())
	return err == nil
}

// launchdPID returns the pid of the running job, or 0 when the job is
// registered but has no process — never started, crashed, or on its way out.
func launchdPID() int {
	out, err := runLaunchctl("print", launchdTarget())
	if err != nil {
		return 0
	}
	for line := range strings.SplitSeq(out, "\n") {
		line = strings.TrimSpace(line)
		if rest, ok := strings.CutPrefix(line, "pid = "); ok {
			if pid, err := strconv.Atoi(strings.TrimSpace(rest)); err == nil {
				return pid
			}
		}
	}
	return 0
}

// launchdBootout removes the job and waits for it to actually leave the domain.
// Bootstrapping the same label inside the drain window fails with an
// "Input/output error" that reads like a permissions problem.
func launchdBootout() error {
	_, _ = runLaunchctl("bootout", launchdTarget())
	for range 50 {
		if !launchdLoaded() {
			return nil
		}
		time.Sleep(200 * time.Millisecond)
	}
	return fmt.Errorf("launchd job %s did not leave the domain", launchdLabel)
}

// launchdBootstrap loads the agent, draining any previous instance first. The
// whole cycle is retried: a domain that was busy on the first attempt is
// usually ready on the second.
func launchdBootstrap() error {
	path, err := plistPath()
	if err != nil {
		return err
	}
	var lastOut string
	for range 3 {
		if err := launchdBootout(); err != nil {
			return err
		}
		out, err := runLaunchctl("bootstrap", launchdDomain(), path)
		lastOut = out
		if err == nil && launchdLoaded() {
			return nil
		}
		time.Sleep(time.Second)
	}
	return fmt.Errorf("could not bootstrap %s: %s", launchdLabel, strings.TrimSpace(lastOut))
}

// startServer brings the server up.
//
// With KeepAlive=false the job may be loaded but idle, so "start" is two steps:
// make sure the label is in the domain, then kickstart the process. kickstart
// on an already-running job is a no-op restart, which is the right behaviour
// for a menu item that means "make it run".
func startServer() error {
	if !launchdLoaded() {
		if err := launchdBootstrap(); err != nil {
			return err
		}
	}
	if out, err := runLaunchctl("kickstart", launchdTarget()); err != nil {
		return fmt.Errorf("kickstart: %s", strings.TrimSpace(out))
	}
	return nil
}

// stopServer sends SIGTERM to the running process and leaves the job loaded.
//
// Not `bootout`: the server handles SIGTERM and drains, and booting the label
// out would put every subsequent Start through the drain race for no gain. The
// job staying loaded-but-idle is exactly what KeepAlive=false is for.
func stopServer() error {
	if !launchdLoaded() {
		return nil
	}
	out, err := runLaunchctl("kill", "SIGTERM", launchdTarget())
	if err != nil {
		// "No such process" is success from the user's point of view: the job
		// is loaded, nothing is running, which is what they asked for.
		if strings.Contains(out, "No such process") || launchdPID() == 0 {
			return nil
		}
		return fmt.Errorf("kill: %s", strings.TrimSpace(out))
	}
	return nil
}

// writeLaunchdFiles regenerates the wrapper and the plist.
//
// Called on every launch. It no longer has to chase a moving bundle — the
// wrapper execs ~/.cix/runtime/current/cix-server, a path that survives both an
// app that was moved and a runtime that was updated — but it is still what puts
// the files back if something else overwrote them.
func writeLaunchdFiles(runAtLoad bool) error {
	server, err := runtimeServerPath()
	if err != nil {
		return err
	}
	wrapper, err := wrapperPath()
	if err != nil {
		return err
	}
	plist, err := plistPath()
	if err != nil {
		return err
	}
	logs, err := logDir()
	if err != nil {
		return err
	}
	envPath, err := serverEnvPath()
	if err != nil {
		return err
	}

	for _, dir := range []string{filepath.Dir(wrapper), filepath.Dir(plist), logs} {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}

	// The wrapper holds all the configuration indirection so the plist stays
	// static: launchd only re-reads a plist at bootstrap, but the wrapper is
	// read afresh on every start, so editing server.env and restarting is
	// enough. CIX_LLAMA_BIN_DIR is not set — cix-server resolves llama/ next to
	// its own executable, and inside the runtime directory that is already
	// correct, through the symlink or resolved past it.
	//
	// It execs the `current` symlink rather than the versioned directory behind
	// it. That is the whole point of the symlink: a runtime update swaps where
	// it points and this file does not change, so no plist rewrite and no
	// bootout/bootstrap cycle is needed to pick up a new server.
	script := fmt.Sprintf(`#!/usr/bin/env bash
%s
# Generated by cix.app — launchd entry point for cix-server.
# Regenerated on every app launch; edit ~/.cix/server.env instead.
set -euo pipefail
set -a
source %q
set +a
exec %q
`, managedByMarker, envPath, server)

	if err := os.WriteFile(wrapper, []byte(script), 0o755); err != nil {
		return err
	}
	if err := os.Chmod(wrapper, 0o755); err != nil {
		return err
	}

	runAtLoadXML := "<false/>"
	if runAtLoad {
		runAtLoadXML = "<true/>"
	}

	// KeepAlive=false, a deliberate divergence from install-server.sh.
	// With KeepAlive=true, Stop has to be a bootout (launchd would restart
	// anything it merely killed), which drags the drain race onto the hot path
	// of a menu click. The trade is that a crashed server is not resurrected —
	// acceptable when a menu bar item shows it as stopped within five seconds.
	doc := fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>%s</string>
  <key>ProgramArguments</key>
  <array><string>%s</string></array>
  <key>RunAtLoad</key>%s
  <key>KeepAlive</key><false/>
  <key>StandardOutPath</key><string>%s</string>
  <key>StandardErrorPath</key><string>%s</string>
</dict></plist>
`, launchdLabel, wrapper, runAtLoadXML,
		filepath.Join(logs, "cix-server.log"),
		filepath.Join(logs, "cix-server.err"))

	return os.WriteFile(plist, []byte(doc), 0o644)
}

// autostartEnabled reads RunAtLoad back out of the installed plist.
//
// The plist is regenerated on every app launch and on every Start, so this is
// what stops that regeneration from quietly resetting the user's autostart
// choice. Absent plist means absent choice, which is off. (The menu toggle that
// sets it is Phase 3; this reader is what makes adding it safe.)
func autostartEnabled() bool {
	path, err := plistPath()
	if err != nil {
		return false
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	// Deliberately not a plist parser: we generate this file ourselves, on one
	// line, in a known shape. A foreign plist is handled by foreignAgent, which
	// takes the app out of the business of writing it at all.
	body := string(data)
	idx := strings.Index(body, "<key>RunAtLoad</key>")
	if idx < 0 {
		return false
	}
	rest := body[idx+len("<key>RunAtLoad</key>"):]
	return strings.HasPrefix(strings.TrimSpace(rest), "<true/>")
}

// setAutostart flips RunAtLoad and reloads the agent.
//
// The reload is not optional and cannot be skipped by kickstarting instead:
// launchd reads a plist exactly once, when the job is bootstrapped into the
// domain. A rewritten plist with the job still loaded changes nothing at all
// until the next login — which is precisely the setting being changed, so the
// user would find out months later.
//
// Rebootstrapping restarts a running server. That is why the caller restores
// the process afterwards rather than this function pretending the cost is zero.
func setAutostart(enabled bool) error {
	if err := writeLaunchdFiles(enabled); err != nil {
		return err
	}
	return launchdBootstrap()
}

// foreignAgent reports whether a launchd agent under our label exists but was
// set up by something else — in practice install-server.sh, which uses the same
// label (:44) but points it at a repo checkout (:351).
//
// Clobbering it would silently repoint a developer's working install at the
// bundle. The app goes observe-only instead: status, provider and dashboard
// still work over HTTP, but Start/Stop are disabled and labelled.
func foreignAgent() bool {
	plist, err := plistPath()
	if err != nil {
		return false
	}
	if _, err := os.Stat(plist); err != nil {
		return false // nothing there at all; ours to create
	}
	wrapper, err := wrapperPath()
	if err != nil {
		return false
	}
	data, err := os.ReadFile(wrapper)
	if err != nil {
		// A plist exists but its wrapper does not, or is unreadable: not ours.
		return true
	}
	return !strings.Contains(string(data), managedByMarker)
}

// serverDiedOnStart reports why the server is already gone after a Start we
// asked for, or "" when it is still alive.
//
// launchctl answers for having spawned the process, not for the process
// surviving it. A server that rejects its own configuration exits in
// milliseconds and leaves the menu reading "Stopped" with no explanation —
// indistinguishable from a Start button that does nothing.
//
// The wait is two-sided on purpose: a pid takes a moment to appear, and a
// process that is going to die does it almost at once. Neither half is a
// deadline for anything the user waits on — a healthy server returns from here
// as soon as it has a pid.
func serverDiedOnStart() string {
	deadline := time.Now().Add(3 * time.Second)
	for time.Now().Before(deadline) && launchdPID() == 0 {
		time.Sleep(200 * time.Millisecond)
	}
	time.Sleep(2 * time.Second)
	if launchdPID() != 0 {
		return ""
	}
	return lastServerError()
}

// lastServerError pulls the tail of cix-server.err, for a dialog.
//
// The server writes its refusals there as plain prose across several lines, so
// the last few non-empty ones are the message. Capped: an unbounded log tail in
// a modal dialog is its own failure.
func lastServerError() string {
	dir, err := logDir()
	if err != nil {
		return "The server exited immediately."
	}
	data, err := os.ReadFile(filepath.Join(dir, "cix-server.err"))
	if err != nil {
		return "The server exited immediately."
	}

	var lines []string
	for line := range strings.SplitSeq(string(data), "\n") {
		if strings.TrimSpace(line) != "" {
			lines = append(lines, strings.TrimRight(line, " \t"))
		}
	}
	if len(lines) == 0 {
		return "The server exited immediately, without logging anything."
	}
	const keep = 8
	if len(lines) > keep {
		lines = lines[len(lines)-keep:]
	}

	out := strings.Join(lines, "\n")
	const maxRunes = 900
	if r := []rune(out); len(r) > maxRunes {
		out = "…" + string(r[len(r)-maxRunes:])
	}
	return out
}
