package tsgrammar

// Code generated by vendor.sh — DO NOT EDIT.
// Grammar: DerekStride/tree-sitter-sql @ v0.3.11 (src)

// #cgo CFLAGS: -std=c11 -fPIC -I${SRCDIR}
// typedef struct TSLanguage TSLanguage;
// const TSLanguage *tree_sitter_sql(void);
import "C"
import "unsafe"

// Language returns the C TSLanguage pointer for sql.
func Language() unsafe.Pointer { return unsafe.Pointer(C.tree_sitter_sql()) }
