package tsgrammar

// Code generated by vendor.sh — DO NOT EDIT.
// Grammar: r-lib/tree-sitter-r @ v1.2.0 (src)

// #cgo CFLAGS: -std=c11 -fPIC -I${SRCDIR}
// typedef struct TSLanguage TSLanguage;
// const TSLanguage *tree_sitter_r(void);
import "C"
import "unsafe"

// Language returns the C TSLanguage pointer for r.
func Language() unsafe.Pointer { return unsafe.Pointer(C.tree_sitter_r()) }
