package secrets

import (
	"bytes"
	"encoding/hex"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRoundTrip(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("CIX_SECRET_KEY", "")
	t.Setenv("CIX_SECRET_KEYFILE", "")

	svc, err := Open(OpenOptions{DataDir: dir, AllowGenerate: true})
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if !svc.Autogenerated() {
		t.Fatalf("expected autogenerated keyfile")
	}
	plain := []byte("ghp_super_secret_token_value")
	ct, err := svc.Encrypt(plain)
	if err != nil {
		t.Fatalf("Encrypt: %v", err)
	}
	if bytes.Contains(ct, plain) {
		t.Fatalf("ciphertext leaked plaintext bytes")
	}
	got, err := svc.Decrypt(ct)
	if err != nil {
		t.Fatalf("Decrypt: %v", err)
	}
	if !bytes.Equal(got, plain) {
		t.Fatalf("roundtrip mismatch: got %q want %q", got, plain)
	}
}

func TestPersistentKeyfile(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("CIX_SECRET_KEY", "")
	t.Setenv("CIX_SECRET_KEYFILE", "")

	svc1, err := Open(OpenOptions{DataDir: dir, AllowGenerate: true})
	if err != nil {
		t.Fatalf("first Open: %v", err)
	}
	ct, err := svc1.Encrypt([]byte("hello"))
	if err != nil {
		t.Fatalf("Encrypt: %v", err)
	}

	// Second Open in the same dir must reuse the keyfile (NOT regenerate).
	svc2, err := Open(OpenOptions{DataDir: dir, AllowGenerate: true})
	if err != nil {
		t.Fatalf("second Open: %v", err)
	}
	if svc2.Autogenerated() {
		t.Fatalf("second Open should reuse the existing keyfile, not regenerate")
	}
	plain, err := svc2.Decrypt(ct)
	if err != nil {
		t.Fatalf("Decrypt with reused key: %v", err)
	}
	if string(plain) != "hello" {
		t.Fatalf("unexpected plaintext %q", plain)
	}
}

func TestErrNoKey(t *testing.T) {
	t.Setenv("CIX_SECRET_KEY", "")
	t.Setenv("CIX_SECRET_KEYFILE", "")
	_, err := Open(OpenOptions{AllowGenerate: false})
	if !errors.Is(err, ErrNoKey) {
		t.Fatalf("expected ErrNoKey, got %v", err)
	}
}

func TestEnvKeyHex(t *testing.T) {
	dir := t.TempDir()
	key := bytes.Repeat([]byte{0xAB}, KeySize)
	t.Setenv("CIX_SECRET_KEY", hex.EncodeToString(key))
	t.Setenv("CIX_SECRET_KEYFILE", "")

	svc, err := Open(OpenOptions{DataDir: dir})
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if !strings.HasPrefix(svc.Source(), "env:") {
		t.Fatalf("expected env source, got %q", svc.Source())
	}
	ct, _ := svc.Encrypt([]byte("x"))
	got, err := svc.Decrypt(ct)
	if err != nil {
		t.Fatalf("Decrypt: %v", err)
	}
	if string(got) != "x" {
		t.Fatalf("unexpected plaintext")
	}
}

func TestKeyFileBadPerms(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "key")
	key := bytes.Repeat([]byte{0xCD}, KeySize)
	if err := os.WriteFile(path, []byte(hex.EncodeToString(key)), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	t.Setenv("CIX_SECRET_KEY", "")
	t.Setenv("CIX_SECRET_KEYFILE", path)
	_, err := Open(OpenOptions{})
	if err == nil {
		t.Fatalf("expected error for 0644 keyfile")
	}
	if !strings.Contains(err.Error(), "insecure permissions") {
		t.Fatalf("expected permission error, got %v", err)
	}
}

func TestDecryptTampered(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("CIX_SECRET_KEY", "")
	t.Setenv("CIX_SECRET_KEYFILE", "")
	svc, err := Open(OpenOptions{DataDir: dir, AllowGenerate: true})
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	ct, _ := svc.Encrypt([]byte("payload"))
	// Flip a byte in the body — must trigger AEAD failure.
	ct[len(ct)-1] ^= 0xFF
	if _, err := svc.Decrypt(ct); err == nil {
		t.Fatalf("expected decrypt failure on tampered ciphertext")
	}
}

func TestDecryptUnknownVersion(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("CIX_SECRET_KEY", "")
	t.Setenv("CIX_SECRET_KEYFILE", "")
	svc, err := Open(OpenOptions{DataDir: dir, AllowGenerate: true})
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	ct, _ := svc.Encrypt([]byte("payload"))
	ct[0] = 0xFE // unknown version byte
	if _, err := svc.Decrypt(ct); !errors.Is(err, ErrUnknownVersion) {
		t.Fatalf("expected ErrUnknownVersion, got %v", err)
	}
}

func TestDecryptTooShort(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("CIX_SECRET_KEY", "")
	t.Setenv("CIX_SECRET_KEYFILE", "")
	svc, err := Open(OpenOptions{DataDir: dir, AllowGenerate: true})
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if _, err := svc.Decrypt([]byte{0x01, 0x02}); !errors.Is(err, ErrCiphertextTooShort) {
		t.Fatalf("expected ErrCiphertextTooShort, got %v", err)
	}
}

func TestConstantTimeEqual(t *testing.T) {
	if !ConstantTimeEqual([]byte("abc"), []byte("abc")) {
		t.Fatal("equal slices should compare equal")
	}
	if ConstantTimeEqual([]byte("abc"), []byte("abcd")) {
		t.Fatal("different-length slices should not compare equal")
	}
	if ConstantTimeEqual([]byte("abc"), []byte("abd")) {
		t.Fatal("different slices should not compare equal")
	}
}
