package tsgrammar

// Code generated by vendor.sh — DO NOT EDIT.
// Grammar: JoranHonig/tree-sitter-solidity @ v1.2.13 (src)

// #cgo CFLAGS: -std=c11 -fPIC -I${SRCDIR}
// typedef struct TSLanguage TSLanguage;
// const TSLanguage *tree_sitter_solidity(void);
import "C"
import "unsafe"

// Language returns the C TSLanguage pointer for solidity.
func Language() unsafe.Pointer { return unsafe.Pointer(C.tree_sitter_solidity()) }
