// Package chunksfts maintains the BM25-searchable FTS5 mirror of every
// chunk that lives in the chromem-go vector store.
//
// We index the same chunk content (plus symbol_name and file_path) into
// a trigram-tokenized FTS5 virtual table so that workspace search can
// combine dense vector retrieval with sparse keyword retrieval. The
// sparse signal serves two roles:
//
//  1. Acronym / short-token precision. Short product codes and
//     unique identifiers get diffuse cosine scores from the embedding
//     model — BM25 over literal tokens recovers the precision.
//
//  2. Project-relevance gating. Pure dense fan-out returns N nearest
//     vectors from every project's chromem collection regardless of
//     semantic distance, so projects that share zero vocabulary with
//     the query still show up at chunk_score ~0.2-0.3. BM25 returning
//     zero hits is a strong "this project has nothing" signal that
//     dense alone cannot produce.
//
// chunks_fts is filterable only by rowid; chunks_meta is the regular
// indexed shadow that lets us look up (and delete) the rows belonging
// to a given (project_path, file_path) pair efficiently. The two
// tables are kept consistent inside the indexer's per-file SQL
// transaction.
package chunksfts

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
)

// Chunk is the unit the indexer hands us. Mirrors vectorstore.Chunk
// with only the fields BM25 indexing cares about — the embedding stays
// in chromem.
type Chunk struct {
	Content    string
	FilePath   string
	StartLine  int
	EndLine    int
	ChunkType  string
	SymbolName string
	Language   string
}

// Hit is one BM25 ranking row.
type Hit struct {
	FilePath   string
	StartLine  int
	EndLine    int
	ChunkType  string
	SymbolName string
	Language   string
	Content    string
	// Score is positive ("higher is better"). SQLite's bm25() returns
	// negative values where smaller = more relevant; we flip the sign
	// at the storage boundary so callers don't need to know.
	Score float64
}

// UpsertByFileTx replaces the FTS rows for one (project_path, file_path)
// pair atomically inside the caller's transaction. Existing rows for the
// pair are deleted first, then the new chunks are inserted. Both tables
// (chunks_meta and chunks_fts) are kept in sync via a per-row rowid
// generated by chunks_meta's autoincrement primary key.
//
// The caller (indexer) wraps this in the same per-file SQL tx that
// commits symbols/refs/file_hashes, so a tx rollback unwinds every
// SQLite-side change for the file atomically.
func UpsertByFileTx(ctx context.Context, tx *sql.Tx, projectPath, filePath string, chunks []Chunk) error {
	if err := DeleteByFileTx(ctx, tx, projectPath, filePath); err != nil {
		return err
	}
	if len(chunks) == 0 {
		return nil
	}
	metaStmt, err := tx.PrepareContext(ctx,
		`INSERT INTO chunks_meta
		 (project_path, file_path, start_line, end_line, chunk_type, symbol_name, language)
		 VALUES (?, ?, ?, ?, ?, ?, ?)`,
	)
	if err != nil {
		return fmt.Errorf("prepare chunks_meta insert: %w", err)
	}
	defer metaStmt.Close()

	ftsStmt, err := tx.PrepareContext(ctx,
		`INSERT INTO chunks_fts(rowid, content, symbol_name, file_path)
		 VALUES (?, ?, ?, ?)`,
	)
	if err != nil {
		return fmt.Errorf("prepare chunks_fts insert: %w", err)
	}
	defer ftsStmt.Close()

	for _, c := range chunks {
		res, err := metaStmt.ExecContext(ctx,
			projectPath, filePath,
			c.StartLine, c.EndLine,
			nullIfEmpty(c.ChunkType),
			nullIfEmpty(c.SymbolName),
			nullIfEmpty(c.Language),
		)
		if err != nil {
			return fmt.Errorf("insert chunks_meta: %w", err)
		}
		rowid, err := res.LastInsertId()
		if err != nil {
			return fmt.Errorf("chunks_meta LastInsertId: %w", err)
		}
		if _, err := ftsStmt.ExecContext(ctx, rowid, c.Content, c.SymbolName, c.FilePath); err != nil {
			return fmt.Errorf("insert chunks_fts: %w", err)
		}
	}
	return nil
}

// DeleteByFileTx removes the BM25 rows for one (project_path, file_path).
// chunks_fts must be cleared via rowid IN (SELECT rowid FROM chunks_meta
// WHERE ...) because FTS5 cannot filter directly on unindexed metadata.
func DeleteByFileTx(ctx context.Context, tx *sql.Tx, projectPath, filePath string) error {
	if _, err := tx.ExecContext(ctx,
		`DELETE FROM chunks_fts
		 WHERE rowid IN (
		   SELECT rowid FROM chunks_meta WHERE project_path = ? AND file_path = ?
		 )`,
		projectPath, filePath,
	); err != nil {
		return fmt.Errorf("delete chunks_fts: %w", err)
	}
	if _, err := tx.ExecContext(ctx,
		`DELETE FROM chunks_meta WHERE project_path = ? AND file_path = ?`,
		projectPath, filePath,
	); err != nil {
		return fmt.Errorf("delete chunks_meta: %w", err)
	}
	return nil
}

// deleteBatchSize bounds one wipe batch. FTS5 deletes re-tokenize each row's
// content to remove its postings — with the trigram tokenizer and ~4.5 KB
// chunks that is by far the most expensive delete in the schema, so the batch
// is sized to keep each transaction well under a second. The point of
// batching: SQLite has ONE writer, and a monolithic project wipe (vscode-sized
// projects: tens of thousands of FTS rows) held the write lock for minutes,
// starving every other writer past busy_timeout (the prod symptom: jobs-worker
// `claim failed: SQLITE_BUSY` every poll tick for the whole wipe).
const deleteBatchSize = 500

// DeleteByProject wipes a project's BM25 rows in bounded batches, one
// transaction per batch, releasing the SQLite writer between batches so
// concurrent writers (jobs queue, dashboard, other indexing runs) interleave.
//
// NOT atomic as a whole: a crash mid-wipe leaves the tail in place. Callers
// (full-reindex wipe, project delete) tolerate that — the next wipe attempt
// resumes where this one stopped, and orphaned rows are invisible to search
// once the project row / file_hashes are gone.
//
// Both subselects inside a batch tx see the same snapshot and use
// ORDER BY rowid, so the fts and meta deletes target the identical row set.
func DeleteByProject(ctx context.Context, db *sql.DB, projectPath string) error {
	for {
		tx, err := db.BeginTx(ctx, nil)
		if err != nil {
			return err
		}
		if _, err := tx.ExecContext(ctx,
			`DELETE FROM chunks_fts
			 WHERE rowid IN (SELECT rowid FROM chunks_meta
			                  WHERE project_path = ? ORDER BY rowid LIMIT ?)`,
			projectPath, deleteBatchSize,
		); err != nil {
			tx.Rollback() //nolint:errcheck
			return fmt.Errorf("delete chunks_fts batch: %w", err)
		}
		res, err := tx.ExecContext(ctx,
			`DELETE FROM chunks_meta
			 WHERE rowid IN (SELECT rowid FROM chunks_meta
			                  WHERE project_path = ? ORDER BY rowid LIMIT ?)`,
			projectPath, deleteBatchSize,
		)
		if err != nil {
			tx.Rollback() //nolint:errcheck
			return fmt.Errorf("delete chunks_meta batch: %w", err)
		}
		n, _ := res.RowsAffected()
		if err := tx.Commit(); err != nil {
			return err
		}
		if n < deleteBatchSize {
			return nil
		}
	}
}

// SearchProject runs an OR-joined trigram FTS5 query restricted to a
// single project and returns up to `limit` chunks ranked by BM25.
//
// Empty or all-tokens-too-short queries return a nil slice without
// hitting the DB — there is nothing to match.
func SearchProject(ctx context.Context, db *sql.DB, projectPath, query string, limit int) ([]Hit, error) {
	if limit <= 0 {
		limit = 20
	}
	fts5Q := buildFTS5Query(query)
	if fts5Q == "" {
		return nil, nil
	}
	rows, err := db.QueryContext(ctx,
		`SELECT cm.file_path, cm.start_line, cm.end_line,
		        cm.chunk_type, cm.symbol_name, cm.language,
		        cf.content, bm25(chunks_fts) AS bm
		 FROM chunks_fts cf
		 JOIN chunks_meta cm ON cm.rowid = cf.rowid
		 WHERE chunks_fts MATCH ? AND cm.project_path = ?
		 ORDER BY bm ASC
		 LIMIT ?`,
		fts5Q, projectPath, limit,
	)
	if err != nil {
		return nil, fmt.Errorf("chunks_fts search: %w", err)
	}
	defer rows.Close()
	var out []Hit
	for rows.Next() {
		var (
			h        Hit
			chunkT   sql.NullString
			symName  sql.NullString
			language sql.NullString
			bm       float64
		)
		if err := rows.Scan(&h.FilePath, &h.StartLine, &h.EndLine,
			&chunkT, &symName, &language, &h.Content, &bm); err != nil {
			return nil, fmt.Errorf("scan chunks_fts row: %w", err)
		}
		h.ChunkType = chunkT.String
		h.SymbolName = symName.String
		h.Language = language.String
		// SQLite returns more-negative bm25 for better matches. Flip so
		// callers can blend with cosine-style "higher is better" scores.
		h.Score = -bm
		out = append(out, h)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate chunks_fts: %w", err)
	}
	return out, nil
}

// buildFTS5Query turns a free-text query into a safe FTS5 expression:
// each whitespace-separated word becomes a double-quoted phrase, all
// phrases are OR-joined. Single-character tokens are dropped (trigram
// tokenizer falls back to prefix-search for sub-3 tokens which is
// noisy). Internal double quotes are doubled per the FTS5 grammar.
func buildFTS5Query(q string) string {
	words := strings.Fields(q)
	parts := make([]string, 0, len(words))
	for _, w := range words {
		w = strings.TrimSpace(w)
		if len([]rune(w)) < 2 {
			continue
		}
		w = strings.ReplaceAll(w, `"`, `""`)
		parts = append(parts, `"`+w+`"`)
	}
	return strings.Join(parts, " OR ")
}

func nullIfEmpty(s string) any {
	if s == "" {
		return nil
	}
	return s
}
