#!/usr/bin/env bash
# Vendors the few tree-sitter C grammars that have NO usable upstream Go module
# (no bindings/go, or — for sql — no committed generated parser.c, or — for r —
# a binding that omits the external scanner so it fails to link). Everything
# else is consumed as a Go module; see registry.go.
#
# Each vendored grammar becomes its own cgo package under tsgrammars/<id>/.
# Re-runnable. Pins are recorded here and in grammars.lock.
#
# Usage: ./vendor.sh [id ...]   (no args = all holdouts)
set -uo pipefail
cd "$(dirname "$0")"
HERE="$(pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# id | repo | ref | src-subdir | c-func | needs-generate(0/1)
MANIFEST=$(cat <<'EOF'
markdown|tree-sitter-grammars/tree-sitter-markdown|v0.5.3|tree-sitter-markdown/src|tree_sitter_markdown|0
objc|tree-sitter-grammars/tree-sitter-objc|v3.0.2|src|tree_sitter_objc|0
scss|tree-sitter-grammars/tree-sitter-scss|v1.0.0|src|tree_sitter_scss|0
solidity|JoranHonig/tree-sitter-solidity|v1.2.13|src|tree_sitter_solidity|0
sql|DerekStride/tree-sitter-sql|v0.3.11|src|tree_sitter_sql|1
r|r-lib/tree-sitter-r|v1.2.0|src|tree_sitter_r|0
EOF
)

WANT="${*:-}"
want() { [ -z "$WANT" ] && return 0; for w in $WANT; do [ "$w" = "$1" ] && return 0; done; return 1; }

clone() { # repo ref destdir
  local repo="$1" ref="$2" dest="$3"
  if git clone --depth 1 --branch "$ref" "https://github.com/$repo" "$dest" >/dev/null 2>&1; then return 0; fi
  git clone "https://github.com/$repo" "$dest" >/dev/null 2>&1 || return 1
  git -C "$dest" checkout "$ref" >/dev/null 2>&1 || return 1
}

ok=0; fail=0; FAILED=""
while IFS='|' read -r key repo ref subdir func gen; do
  [ -z "$key" ] && continue
  want "$key" || continue
  printf '%-12s %s@%s ... ' "$key" "$repo" "$ref"
  repodir="$WORK/$key"
  rm -rf "$repodir"
  if ! clone "$repo" "$ref" "$repodir"; then echo "CLONE FAIL"; fail=$((fail+1)); FAILED="$FAILED $key"; continue; fi
  srcdir="$repodir/$subdir"
  if [ "$gen" = "1" ] && [ ! -f "$srcdir/parser.c" ]; then
    command -v tree-sitter >/dev/null 2>&1 && (cd "$repodir" && tree-sitter generate >/dev/null 2>&1)
  fi
  if [ ! -f "$srcdir/parser.c" ]; then echo "NO parser.c"; fail=$((fail+1)); FAILED="$FAILED $key"; continue; fi

  out="$HERE/$key"
  rm -rf "$out"; mkdir -p "$out"
  cp "$srcdir/parser.c" "$out/"
  [ -f "$srcdir/scanner.c" ] && cp "$srcdir/scanner.c" "$out/"
  [ -f "$srcdir/scanner.cc" ] && cp "$srcdir/scanner.cc" "$out/"
  [ -d "$srcdir/tree_sitter" ] && cp -r "$srcdir/tree_sitter" "$out/"
  # Extra headers that live in the src root (e.g. html tag.h, haskell unicode.h).
  for h in "$srcdir"/*.h; do [ -f "$h" ] && cp "$h" "$out/"; done

  # Rewrite relative includes that point outside src (e.g. typescript's shared
  # ../../common/scanner.h) to a local copy.
  for sc in "$out"/scanner.c "$out"/scanner.cc; do
    [ -f "$sc" ] || continue
    grep -oE '#include "(\.\./)+[^"]+"' "$sc" 2>/dev/null | sed -E 's/#include "//; s/"$//' | while read -r inc; do
      base="$(basename "$inc")"
      resolved="$srcdir/$inc"
      if [ -f "$resolved" ]; then
        cp "$resolved" "$out/$base"
        sed -i '' "s#\"$inc\"#\"$base\"#" "$sc" 2>/dev/null || sed -i "s#\"$inc\"#\"$base\"#" "$sc"
      fi
    done
  done

  cxxld=""
  [ -f "$out/scanner.cc" ] && cxxld="// #cgo LDFLAGS: -lstdc++"$'\n'
  cat > "$out/binding.go" <<GO
package tsgrammar

// Code generated by vendor.sh — DO NOT EDIT.
// Grammar: $repo @ $ref ($subdir)

// #cgo CFLAGS: -std=c11 -fPIC -I\${SRCDIR}
${cxxld}// typedef struct TSLanguage TSLanguage;
// const TSLanguage *$func(void);
import "C"
import "unsafe"

// Language returns the C TSLanguage pointer for $key.
func Language() unsafe.Pointer { return unsafe.Pointer(C.$func()) }
GO
  echo "ok"
  ok=$((ok+1))
done <<< "$MANIFEST"

echo "------ vendored: $ok  failed: $fail ${FAILED:+(failed:$FAILED)}"
