// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for CreateUserRequestRole.
const (
	CreateUserRequestRoleAdmin  CreateUserRequestRole = "admin"
	CreateUserRequestRoleViewer CreateUserRequestRole = "viewer"
)

// Valid indicates whether the value is a known member of the CreateUserRequestRole enum.
func (e CreateUserRequestRole) Valid() bool {
	switch e {
	case CreateUserRequestRoleAdmin:
		return true
	case CreateUserRequestRoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusOk        HealthResponseStatus = "ok"
	HealthResponseStatusUnhealthy HealthResponseStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case HealthResponseStatusOk:
		return true
	case HealthResponseStatusUnhealthy:
		return true
	default:
		return false
	}
}

// Defines values for IndexFinishResponseStatus.
const (
	IndexFinishResponseStatusCompleted IndexFinishResponseStatus = "completed"
)

// Valid indicates whether the value is a known member of the IndexFinishResponseStatus enum.
func (e IndexFinishResponseStatus) Valid() bool {
	switch e {
	case IndexFinishResponseStatusCompleted:
		return true
	default:
		return false
	}
}

// Defines values for IndexProgressEventEvent.
const (
	IndexProgressEventEventBatchDone    IndexProgressEventEvent = "batch_done"
	IndexProgressEventEventError        IndexProgressEventEvent = "error"
	IndexProgressEventEventFileChunked  IndexProgressEventEvent = "file_chunked"
	IndexProgressEventEventFileDone     IndexProgressEventEvent = "file_done"
	IndexProgressEventEventFileEmbedded IndexProgressEventEvent = "file_embedded"
	IndexProgressEventEventFileError    IndexProgressEventEvent = "file_error"
	IndexProgressEventEventFileStarted  IndexProgressEventEvent = "file_started"
	IndexProgressEventEventHeartbeat    IndexProgressEventEvent = "heartbeat"
)

// Valid indicates whether the value is a known member of the IndexProgressEventEvent enum.
func (e IndexProgressEventEvent) Valid() bool {
	switch e {
	case IndexProgressEventEventBatchDone:
		return true
	case IndexProgressEventEventError:
		return true
	case IndexProgressEventEventFileChunked:
		return true
	case IndexProgressEventEventFileDone:
		return true
	case IndexProgressEventEventFileEmbedded:
		return true
	case IndexProgressEventEventFileError:
		return true
	case IndexProgressEventEventFileStarted:
		return true
	case IndexProgressEventEventHeartbeat:
		return true
	default:
		return false
	}
}

// Defines values for IndexProgressInfoPhase.
const (
	IndexProgressInfoPhaseCompleted IndexProgressInfoPhase = "completed"
	IndexProgressInfoPhaseReceiving IndexProgressInfoPhase = "receiving"
)

// Valid indicates whether the value is a known member of the IndexProgressInfoPhase enum.
func (e IndexProgressInfoPhase) Valid() bool {
	switch e {
	case IndexProgressInfoPhaseCompleted:
		return true
	case IndexProgressInfoPhaseReceiving:
		return true
	default:
		return false
	}
}

// Defines values for IndexProgressResponseStatus.
const (
	Cancelled IndexProgressResponseStatus = "cancelled"
	Completed IndexProgressResponseStatus = "completed"
	Failed    IndexProgressResponseStatus = "failed"
	Idle      IndexProgressResponseStatus = "idle"
	Indexing  IndexProgressResponseStatus = "indexing"
	Running   IndexProgressResponseStatus = "running"
)

// Valid indicates whether the value is a known member of the IndexProgressResponseStatus enum.
func (e IndexProgressResponseStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Completed:
		return true
	case Failed:
		return true
	case Idle:
		return true
	case Indexing:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for MeResponseAuthMethod.
const (
	MeResponseAuthMethodApiKey  MeResponseAuthMethod = "api_key"
	MeResponseAuthMethodSession MeResponseAuthMethod = "session"
)

// Valid indicates whether the value is a known member of the MeResponseAuthMethod enum.
func (e MeResponseAuthMethod) Valid() bool {
	switch e {
	case MeResponseAuthMethodApiKey:
		return true
	case MeResponseAuthMethodSession:
		return true
	default:
		return false
	}
}

// Defines values for ProjectStatus.
const (
	ProjectStatusCreated  ProjectStatus = "created"
	ProjectStatusError    ProjectStatus = "error"
	ProjectStatusIndexed  ProjectStatus = "indexed"
	ProjectStatusIndexing ProjectStatus = "indexing"
)

// Valid indicates whether the value is a known member of the ProjectStatus enum.
func (e ProjectStatus) Valid() bool {
	switch e {
	case ProjectStatusCreated:
		return true
	case ProjectStatusError:
		return true
	case ProjectStatusIndexed:
		return true
	case ProjectStatusIndexing:
		return true
	default:
		return false
	}
}

// Defines values for ReferenceItemChunkType.
const (
	Reference ReferenceItemChunkType = "reference"
)

// Valid indicates whether the value is a known member of the ReferenceItemChunkType enum.
func (e ReferenceItemChunkType) Valid() bool {
	switch e {
	case Reference:
		return true
	default:
		return false
	}
}

// Defines values for StatusResponseStatus.
const (
	StatusResponseStatusOk StatusResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the StatusResponseStatus enum.
func (e StatusResponseStatus) Valid() bool {
	switch e {
	case StatusResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for UpdateUserRequestRole.
const (
	UpdateUserRequestRoleAdmin  UpdateUserRequestRole = "admin"
	UpdateUserRequestRoleViewer UpdateUserRequestRole = "viewer"
)

// Valid indicates whether the value is a known member of the UpdateUserRequestRole enum.
func (e UpdateUserRequestRole) Valid() bool {
	switch e {
	case UpdateUserRequestRoleAdmin:
		return true
	case UpdateUserRequestRoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	Admin  UserRole = "admin"
	Viewer UserRole = "viewer"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// Defines values for ListApiKeysParamsOwner.
const (
	All ListApiKeysParamsOwner = "all"
)

// Valid indicates whether the value is a known member of the ListApiKeysParamsOwner enum.
func (e ListApiKeysParamsOwner) Valid() bool {
	switch e {
	case All:
		return true
	default:
		return false
	}
}

// Defines values for IndexFilesParamsAccept.
const (
	Applicationjson    IndexFilesParamsAccept = "application/json"
	ApplicationxNdjson IndexFilesParamsAccept = "application/x-ndjson"
)

// Valid indicates whether the value is a known member of the IndexFilesParamsAccept enum.
func (e IndexFilesParamsAccept) Valid() bool {
	switch e {
	case Applicationjson:
		return true
	case ApplicationxNdjson:
		return true
	default:
		return false
	}
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt   time.Time  `json:"created_at"`
	Id          string     `json:"id"`
	LastUsedAt  *time.Time `json:"last_used_at,omitempty"`
	LastUsedIp  *string    `json:"last_used_ip,omitempty"`
	LastUsedUa  *string    `json:"last_used_ua,omitempty"`
	Name        string     `json:"name"`
	OwnerUserId string     `json:"owner_user_id"`

	// Prefix Display-only prefix of the full key (e.g. `cix_a1b2c3d4`).
	// Long enough to recognise in lists, short enough that it
	// cannot reconstruct the original.
	Prefix    string     `json:"prefix"`
	Revoked   bool       `json:"revoked"`
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
}

// ApiKeyCreated defines model for ApiKeyCreated.
type ApiKeyCreated struct {
	ApiKey ApiKey `json:"api_key"`

	// FullKey The plaintext key value. **Returned exactly once.** Store it
	// securely — there is no way to retrieve it later.
	FullKey string `json:"full_key"`
}

// ApiKeyListResponse defines model for ApiKeyListResponse.
type ApiKeyListResponse struct {
	ApiKeys []ApiKey `json:"api_keys"`
	Total   int      `json:"total"`
}

// BootstrapStatusResponse defines model for BootstrapStatusResponse.
type BootstrapStatusResponse struct {
	// NeedsBootstrap True when the users table is empty.
	NeedsBootstrap bool `json:"needs_bootstrap"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`

	// NewPassword Minimum 8 characters. No upper bound.
	NewPassword string `json:"new_password"`
}

// CreateApiKeyRequest defines model for CreateApiKeyRequest.
type CreateApiKeyRequest struct {
	// Name Human-friendly label shown in the dashboard. The full key
	// value is generated server-side and returned exactly once.
	Name string `json:"name"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	HostPath string `json:"host_path"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email openapi_types.Email `json:"email"`

	// InitialPassword One-time password the new user must change on first login.
	// The admin shares this out-of-band.
	InitialPassword string                `json:"initial_password"`
	Role            CreateUserRequestRole `json:"role"`
}

// CreateUserRequestRole defines model for CreateUserRequest.Role.
type CreateUserRequestRole string

// DefinitionItem defines model for DefinitionItem.
type DefinitionItem struct {
	EndLine    int     `json:"end_line"`
	FilePath   string  `json:"file_path"`
	Kind       string  `json:"kind"`
	Language   string  `json:"language"`
	Line       int     `json:"line"`
	Name       string  `json:"name"`
	ParentName *string `json:"parent_name,omitempty"`
	Signature  *string `json:"signature,omitempty"`
}

// DefinitionRequest defines model for DefinitionRequest.
type DefinitionRequest struct {
	FilePath *string `json:"file_path,omitempty"`
	Kind     *string `json:"kind,omitempty"`
	Limit    *int    `json:"limit,omitempty"`
	Symbol   string  `json:"symbol"`
}

// DefinitionResponse defines model for DefinitionResponse.
type DefinitionResponse struct {
	Results []DefinitionItem `json:"results"`
	Total   int              `json:"total"`
}

// DirEntry defines model for DirEntry.
type DirEntry struct {
	FileCount int    `json:"file_count"`
	Path      string `json:"path"`
}

// Error defines model for Error.
type Error struct {
	Detail string `json:"detail"`
}

// FileGroupResult defines model for FileGroupResult.
type FileGroupResult struct {
	BestScore float32     `json:"best_score"`
	FilePath  string      `json:"file_path"`
	Language  *string     `json:"language,omitempty"`
	Matches   []FileMatch `json:"matches"`
}

// FileMatch defines model for FileMatch.
type FileMatch struct {
	ChunkType  string       `json:"chunk_type"`
	Content    string       `json:"content"`
	EndLine    int          `json:"end_line"`
	NestedHits *[]NestedHit `json:"nested_hits,omitempty"`
	Score      float32      `json:"score"`
	StartLine  int          `json:"start_line"`
	SymbolName *string      `json:"symbol_name,omitempty"`
}

// FilePayload defines model for FilePayload.
type FilePayload struct {
	// Content UTF-8 text. Binary files should not be submitted.
	Content string `json:"content"`

	// ContentHash SHA-256 hex digest of `content`.
	ContentHash string  `json:"content_hash"`
	Language    *string `json:"language,omitempty"`
	Path        string  `json:"path"`
	Size        int     `json:"size"`
}

// FileResultItem defines model for FileResultItem.
type FileResultItem struct {
	FilePath string `json:"file_path"`

	// Language Detected language, or null if undetected.
	Language *string `json:"language"`
}

// FileSearchRequest defines model for FileSearchRequest.
type FileSearchRequest struct {
	Limit *int `json:"limit,omitempty"`

	// Query Substring matched against `file_path`.
	Query string `json:"query"`
}

// FileSearchResponse defines model for FileSearchResponse.
type FileSearchResponse struct {
	Results []FileResultItem `json:"results"`
	Total   int              `json:"total"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Reason Set only when `status` is `unhealthy`.
	Reason *string              `json:"reason,omitempty"`
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// IndexBeginRequest defines model for IndexBeginRequest.
type IndexBeginRequest struct {
	// Full When true, wipes existing project state before opening the session.
	Full *bool `json:"full,omitempty"`
}

// IndexBeginResponse defines model for IndexBeginResponse.
type IndexBeginResponse struct {
	RunId string `json:"run_id"`

	// StoredHashes Map from file path → SHA-256 of currently-stored content. Empty
	// when the project has never been indexed (or `full:true` was passed).
	StoredHashes map[string]string `json:"stored_hashes"`
}

// IndexCancelResponse defines model for IndexCancelResponse.
type IndexCancelResponse struct {
	Cancelled bool `json:"cancelled"`
}

// IndexFilesRequest defines model for IndexFilesRequest.
type IndexFilesRequest struct {
	Files []FilePayload `json:"files"`
	RunId string        `json:"run_id"`
}

// IndexFilesResponse defines model for IndexFilesResponse.
type IndexFilesResponse struct {
	ChunksCreated       int `json:"chunks_created"`
	FilesAccepted       int `json:"files_accepted"`
	FilesProcessedTotal int `json:"files_processed_total"`
}

// IndexFinishRequest defines model for IndexFinishRequest.
type IndexFinishRequest struct {
	DeletedPaths         *[]string `json:"deleted_paths,omitempty"`
	RunId                string    `json:"run_id"`
	TotalFilesDiscovered *int      `json:"total_files_discovered,omitempty"`
}

// IndexFinishResponse defines model for IndexFinishResponse.
type IndexFinishResponse struct {
	ChunksCreated  int                       `json:"chunks_created"`
	FilesProcessed int                       `json:"files_processed"`
	Status         IndexFinishResponseStatus `json:"status"`
}

// IndexFinishResponseStatus defines model for IndexFinishResponse.Status.
type IndexFinishResponseStatus string

// IndexProgressEvent One event in the NDJSON stream emitted by `POST /index/files` when
// the client sends `Accept: application/x-ndjson`. The `event` field
// discriminates the variant; other fields are populated as relevant.
type IndexProgressEvent struct {
	BatchSize           *int                    `json:"batch_size,omitempty"`
	Chunks              *int                    `json:"chunks,omitempty"`
	ChunksCreated       *int                    `json:"chunks_created,omitempty"`
	EmbedMs             *int64                  `json:"embed_ms,omitempty"`
	Event               IndexProgressEventEvent `json:"event"`
	Fatal               *bool                   `json:"fatal,omitempty"`
	FileIndex           *int                    `json:"file_index,omitempty"`
	FilesAccepted       *int                    `json:"files_accepted,omitempty"`
	FilesProcessedTotal *int                    `json:"files_processed_total,omitempty"`
	Message             *string                 `json:"message,omitempty"`
	Path                *string                 `json:"path,omitempty"`
	RunId               *string                 `json:"run_id,omitempty"`
	Ts                  *time.Time              `json:"ts,omitempty"`
}

// IndexProgressEventEvent defines model for IndexProgressEvent.Event.
type IndexProgressEventEvent string

// IndexProgressInfo Progress payload. The active-session variant carries every field;
// the historical-fallback variant only carries `files_processed`,
// `files_total`, and `chunks_created`.
type IndexProgressInfo struct {
	ChunksCreated   *int                    `json:"chunks_created,omitempty"`
	ElapsedSeconds  *float64                `json:"elapsed_seconds,omitempty"`
	FilesDiscovered *int                    `json:"files_discovered,omitempty"`
	FilesProcessed  *int                    `json:"files_processed,omitempty"`
	FilesTotal      *int                    `json:"files_total,omitempty"`
	Phase           *IndexProgressInfoPhase `json:"phase,omitempty"`
	RunId           *string                 `json:"run_id,omitempty"`
}

// IndexProgressInfoPhase defines model for IndexProgressInfo.Phase.
type IndexProgressInfoPhase string

// IndexProgressResponse defines model for IndexProgressResponse.
type IndexProgressResponse struct {
	// Progress Progress payload. The active-session variant carries every field;
	// the historical-fallback variant only carries `files_processed`,
	// `files_total`, and `chunks_created`.
	Progress *IndexProgressInfo `json:"progress,omitempty"`

	// Status `idle` — no session ever / fallback unavailable.
	// `indexing` — session active.
	// `completed`/`cancelled`/`failed`/`running` — last-run status from `index_runs`.
	Status IndexProgressResponseStatus `json:"status"`
}

// IndexProgressResponseStatus `idle` — no session ever / fallback unavailable.
// `indexing` — session active.
// `completed`/`cancelled`/`failed`/`running` — last-run status from `index_runs`.
type IndexProgressResponseStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	User User `json:"user"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	// AuthMethod Tells the dashboard whether to surface "logout" (session) or
	// hide it (api_key access — there's nothing to log out of).
	AuthMethod MeResponseAuthMethod `json:"auth_method"`
	User       User                 `json:"user"`
}

// MeResponseAuthMethod Tells the dashboard whether to surface "logout" (session) or
// hide it (api_key access — there's nothing to log out of).
type MeResponseAuthMethod string

// NestedHit defines model for NestedHit.
type NestedHit struct {
	ChunkType  string  `json:"chunk_type"`
	EndLine    int     `json:"end_line"`
	Score      float32 `json:"score"`
	StartLine  int     `json:"start_line"`
	SymbolName *string `json:"symbol_name,omitempty"`
}

// Project defines model for Project.
type Project struct {
	// ContainerPath Path inside the container (often equal to host_path).
	ContainerPath string    `json:"container_path"`
	CreatedAt     time.Time `json:"created_at"`

	// HostPath Absolute filesystem path on the operator's machine.
	HostPath      string          `json:"host_path"`
	Languages     []string        `json:"languages"`
	LastIndexedAt *time.Time      `json:"last_indexed_at"`
	Settings      ProjectSettings `json:"settings"`
	Stats         ProjectStats    `json:"stats"`
	Status        ProjectStatus   `json:"status"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

// ProjectStatus defines model for Project.Status.
type ProjectStatus string

// ProjectListResponse defines model for ProjectListResponse.
type ProjectListResponse struct {
	Projects []Project `json:"projects"`
	Total    int       `json:"total"`
}

// ProjectSettings defines model for ProjectSettings.
type ProjectSettings struct {
	ExcludePatterns []string `json:"exclude_patterns"`
	MaxFileSize     int      `json:"max_file_size"`
}

// ProjectStats defines model for ProjectStats.
type ProjectStats struct {
	IndexedFiles int `json:"indexed_files"`
	TotalChunks  int `json:"total_chunks"`
	TotalFiles   int `json:"total_files"`
	TotalSymbols int `json:"total_symbols"`
}

// ProjectSummary defines model for ProjectSummary.
type ProjectSummary struct {
	HostPath       string        `json:"host_path"`
	Languages      []string      `json:"languages"`
	RecentSymbols  []SymbolEntry `json:"recent_symbols"`
	Status         string        `json:"status"`
	TopDirectories []DirEntry    `json:"top_directories"`
	TotalChunks    int           `json:"total_chunks"`
	TotalFiles     int           `json:"total_files"`
	TotalSymbols   int           `json:"total_symbols"`
}

// ReferenceItem defines model for ReferenceItem.
type ReferenceItem struct {
	ChunkType ReferenceItemChunkType `json:"chunk_type"`

	// Content Always empty — see endpoint description.
	Content string `json:"content"`

	// EndLine Always equal to `start_line` (refs table stores tokens, not ranges).
	EndLine    int    `json:"end_line"`
	FilePath   string `json:"file_path"`
	Language   string `json:"language"`
	StartLine  int    `json:"start_line"`
	SymbolName string `json:"symbol_name"`
}

// ReferenceItemChunkType defines model for ReferenceItem.ChunkType.
type ReferenceItemChunkType string

// ReferenceRequest defines model for ReferenceRequest.
type ReferenceRequest struct {
	FilePath *string `json:"file_path,omitempty"`
	Limit    *int    `json:"limit,omitempty"`
	Symbol   string  `json:"symbol"`
}

// ReferenceResponse defines model for ReferenceResponse.
type ReferenceResponse struct {
	Results []ReferenceItem `json:"results"`
	Total   int             `json:"total"`
}

// SemanticSearchRequest defines model for SemanticSearchRequest.
type SemanticSearchRequest struct {
	// Excludes Blacklist — drop results whose path matches any prefix or substring.
	Excludes  *[]string `json:"excludes,omitempty"`
	Languages *[]string `json:"languages,omitempty"`

	// Limit Maximum number of FILE groups (not chunks) to return.
	Limit *int `json:"limit,omitempty"`

	// MinScore Minimum cosine similarity. Omit for server default (0.4 for
	// CodeRankEmbed-Q8). Send `0` explicitly to disable the floor.
	MinScore *float32 `json:"min_score,omitempty"`

	// Paths Whitelist — keep only results whose path matches any prefix or substring.
	Paths *[]string `json:"paths,omitempty"`
	Query string    `json:"query"`
}

// SemanticSearchResponse defines model for SemanticSearchResponse.
type SemanticSearchResponse struct {
	// QueryTimeMs Wall-clock query latency, rounded to 1 decimal place.
	QueryTimeMs float64           `json:"query_time_ms"`
	Results     []FileGroupResult `json:"results"`
	Total       int               `json:"total"`
}

// Session defines model for Session.
type Session struct {
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	Id        string    `json:"id"`

	// IsCurrent True for the session carrying this request.
	IsCurrent  bool      `json:"is_current"`
	LastSeenAt time.Time `json:"last_seen_at"`
	LastSeenIp *string   `json:"last_seen_ip,omitempty"`
	LastSeenUa *string   `json:"last_seen_ua,omitempty"`
}

// SessionListResponse defines model for SessionListResponse.
type SessionListResponse struct {
	Sessions []Session `json:"sessions"`
	Total    int       `json:"total"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	// ActiveIndexingJobs Currently-running `index_runs` rows.
	ActiveIndexingJobs int    `json:"active_indexing_jobs"`
	ApiVersion         string `json:"api_version"`

	// Backend Backend identifier (e.g. `go`).
	Backend string `json:"backend"`

	// EmbeddingModel Hugging Face model id (e.g. `awhiteside/CodeRankEmbed-Q8_0-GGUF`).
	EmbeddingModel string `json:"embedding_model"`

	// ModelLoaded Whether the llama-server sidecar reports ready within 500 ms.
	// False when the sidecar is starting or has crashed.
	ModelLoaded bool `json:"model_loaded"`

	// Projects Total registered projects.
	Projects      int                  `json:"projects"`
	ServerVersion string               `json:"server_version"`
	Status        StatusResponseStatus `json:"status"`
}

// StatusResponseStatus defines model for StatusResponse.Status.
type StatusResponseStatus string

// SymbolEntry defines model for SymbolEntry.
type SymbolEntry struct {
	FilePath string `json:"file_path"`
	Kind     string `json:"kind"`
	Language string `json:"language"`
	Name     string `json:"name"`
}

// SymbolResultItem defines model for SymbolResultItem.
type SymbolResultItem struct {
	EndLine    int     `json:"end_line"`
	FilePath   string  `json:"file_path"`
	Kind       string  `json:"kind"`
	Language   string  `json:"language"`
	Line       int     `json:"line"`
	Name       string  `json:"name"`
	ParentName *string `json:"parent_name,omitempty"`
	Signature  *string `json:"signature,omitempty"`
}

// SymbolSearchRequest defines model for SymbolSearchRequest.
type SymbolSearchRequest struct {
	Kinds *[]string `json:"kinds,omitempty"`
	Limit *int      `json:"limit,omitempty"`
	Query string    `json:"query"`
}

// SymbolSearchResponse defines model for SymbolSearchResponse.
type SymbolSearchResponse struct {
	Results []SymbolResultItem `json:"results"`
	Total   int                `json:"total"`
}

// UpdateProjectRequest defines model for UpdateProjectRequest.
type UpdateProjectRequest struct {
	Settings *ProjectSettings `json:"settings,omitempty"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	// Disabled When true, the user can no longer authenticate. Refused for
	// the last enabled admin when set to true.
	Disabled *bool `json:"disabled,omitempty"`

	// Role New role for the user. Refused for the last enabled admin
	// when set to `viewer`.
	Role *UpdateUserRequestRole `json:"role,omitempty"`
}

// UpdateUserRequestRole New role for the user. Refused for the last enabled admin
// when set to `viewer`.
type UpdateUserRequestRole string

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"created_at"`

	// Disabled True when `disabled_at` is set. Disabled users cannot
	// authenticate via password OR API key.
	Disabled           bool                `json:"disabled"`
	DisabledAt         *time.Time          `json:"disabled_at,omitempty"`
	Email              openapi_types.Email `json:"email"`
	Id                 string              `json:"id"`
	MustChangePassword bool                `json:"must_change_password"`
	Role               UserRole            `json:"role"`
	UpdatedAt          time.Time           `json:"updated_at"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserListResponse defines model for UserListResponse.
type UserListResponse struct {
	Total int    `json:"total"`
	Users []User `json:"users"`
}

// ProjectHash defines model for ProjectHash.
type ProjectHash = string

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// IndexerUnavailable defines model for IndexerUnavailable.
type IndexerUnavailable = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unprocessable defines model for Unprocessable.
type Unprocessable = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListApiKeysParams defines parameters for ListApiKeys.
type ListApiKeysParams struct {
	// Owner `all` — admin-only, returns every key in the system.
	// Anything else (or unset) returns the caller's keys.
	Owner *ListApiKeysParamsOwner `form:"owner,omitempty" json:"owner,omitempty"`
}

// ListApiKeysParamsOwner defines parameters for ListApiKeys.
type ListApiKeysParamsOwner string

// IndexFilesParams defines parameters for IndexFiles.
type IndexFilesParams struct {
	// Accept `application/x-ndjson` switches to a streamed response
	// (one `IndexProgressEvent` per line). Default: `application/json`.
	Accept *IndexFilesParamsAccept `json:"Accept,omitempty"`
}

// IndexFilesParamsAccept defines parameters for IndexFiles.
type IndexFilesParamsAccept string

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateApiKeyRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProjectRequest

// IndexBeginJSONRequestBody defines body for IndexBegin for application/json ContentType.
type IndexBeginJSONRequestBody = IndexBeginRequest

// IndexFilesJSONRequestBody defines body for IndexFiles for application/json ContentType.
type IndexFilesJSONRequestBody = IndexFilesRequest

// IndexFinishJSONRequestBody defines body for IndexFinish for application/json ContentType.
type IndexFinishJSONRequestBody = IndexFinishRequest

// SemanticSearchJSONRequestBody defines body for SemanticSearch for application/json ContentType.
type SemanticSearchJSONRequestBody = SemanticSearchRequest

// SearchDefinitionsJSONRequestBody defines body for SearchDefinitions for application/json ContentType.
type SearchDefinitionsJSONRequestBody = DefinitionRequest

// SearchFilesJSONRequestBody defines body for SearchFiles for application/json ContentType.
type SearchFilesJSONRequestBody = FileSearchRequest

// SearchReferencesJSONRequestBody defines body for SearchReferences for application/json ContentType.
type SearchReferencesJSONRequestBody = ReferenceRequest

// SearchSymbolsJSONRequestBody defines body for SearchSymbols for application/json ContentType.
type SearchSymbolsJSONRequestBody = SymbolSearchRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all users (admin only)
	// (GET /api/v1/admin/users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// Invite a new user (admin only)
	// (POST /api/v1/admin/users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// Delete a user (admin only)
	// (DELETE /api/v1/admin/users/{id})
	DeleteUser(w http.ResponseWriter, r *http.Request, id string)
	// Change role or disabled flag (admin only)
	// (PATCH /api/v1/admin/users/{id})
	UpdateUser(w http.ResponseWriter, r *http.Request, id string)
	// List my API keys (or all keys if admin)
	// (GET /api/v1/api-keys)
	ListApiKeys(w http.ResponseWriter, r *http.Request, params ListApiKeysParams)
	// Issue a new API key
	// (POST /api/v1/api-keys)
	CreateApiKey(w http.ResponseWriter, r *http.Request)
	// Revoke an API key
	// (DELETE /api/v1/api-keys/{id})
	RevokeApiKey(w http.ResponseWriter, r *http.Request, id string)
	// Whether the dashboard needs first-run bootstrap (public)
	// (GET /api/v1/auth/bootstrap-status)
	GetBootstrapStatus(w http.ResponseWriter, r *http.Request)
	// Change the current user's password
	// (POST /api/v1/auth/change-password)
	ChangePassword(w http.ResponseWriter, r *http.Request)
	// Exchange email + password for a session cookie (public)
	// (POST /api/v1/auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// End the current session
	// (POST /api/v1/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Current authenticated user
	// (GET /api/v1/auth/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Active sessions of the current user
	// (GET /api/v1/auth/sessions)
	ListMySessions(w http.ResponseWriter, r *http.Request)
	// End one of my sessions (sign out a single device)
	// (DELETE /api/v1/auth/sessions/{id})
	DeleteMySession(w http.ResponseWriter, r *http.Request, id string)
	// List all registered projects
	// (GET /api/v1/projects)
	ListProjects(w http.ResponseWriter, r *http.Request)
	// Register a new project
	// (POST /api/v1/projects)
	CreateProject(w http.ResponseWriter, r *http.Request)
	// Delete a project (and all its indexed data)
	// (DELETE /api/v1/projects/{path})
	DeleteProject(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Get one project by hash
	// (GET /api/v1/projects/{path})
	GetProject(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Patch project settings
	// (PATCH /api/v1/projects/{path})
	UpdateProject(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Open an indexing session
	// (POST /api/v1/projects/{path}/index/begin)
	IndexBegin(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Cancel any active indexing session (idempotent)
	// (POST /api/v1/projects/{path}/index/cancel)
	IndexCancel(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Submit a batch of files (max 50)
	// (POST /api/v1/projects/{path}/index/files)
	IndexFiles(w http.ResponseWriter, r *http.Request, path ProjectHash, params IndexFilesParams)
	// Commit the indexing session
	// (POST /api/v1/projects/{path}/index/finish)
	IndexFinish(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Live progress of the current run, or last completed run
	// (GET /api/v1/projects/{path}/index/status)
	IndexStatus(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Semantic (vector) search
	// (POST /api/v1/projects/{path}/search)
	SemanticSearch(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Go-to-definition by symbol name
	// (POST /api/v1/projects/{path}/search/definitions)
	SearchDefinitions(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// File-path substring search
	// (POST /api/v1/projects/{path}/search/files)
	SearchFiles(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Find references to a symbol
	// (POST /api/v1/projects/{path}/search/references)
	SearchReferences(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Symbol search by name (prefix/substring)
	// (POST /api/v1/projects/{path}/search/symbols)
	SearchSymbols(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Project overview (top dirs, recent symbols, totals)
	// (GET /api/v1/projects/{path}/summary)
	GetProjectSummary(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Server / sidecar status (authenticated)
	// (GET /api/v1/status)
	GetStatus(w http.ResponseWriter, r *http.Request)
	// Liveness probe (public)
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all users (admin only)
// (GET /api/v1/admin/users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Invite a new user (admin only)
// (POST /api/v1/admin/users)
func (_ Unimplemented) CreateUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a user (admin only)
// (DELETE /api/v1/admin/users/{id})
func (_ Unimplemented) DeleteUser(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Change role or disabled flag (admin only)
// (PATCH /api/v1/admin/users/{id})
func (_ Unimplemented) UpdateUser(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List my API keys (or all keys if admin)
// (GET /api/v1/api-keys)
func (_ Unimplemented) ListApiKeys(w http.ResponseWriter, r *http.Request, params ListApiKeysParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Issue a new API key
// (POST /api/v1/api-keys)
func (_ Unimplemented) CreateApiKey(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke an API key
// (DELETE /api/v1/api-keys/{id})
func (_ Unimplemented) RevokeApiKey(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Whether the dashboard needs first-run bootstrap (public)
// (GET /api/v1/auth/bootstrap-status)
func (_ Unimplemented) GetBootstrapStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Change the current user's password
// (POST /api/v1/auth/change-password)
func (_ Unimplemented) ChangePassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Exchange email + password for a session cookie (public)
// (POST /api/v1/auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// End the current session
// (POST /api/v1/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Current authenticated user
// (GET /api/v1/auth/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Active sessions of the current user
// (GET /api/v1/auth/sessions)
func (_ Unimplemented) ListMySessions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// End one of my sessions (sign out a single device)
// (DELETE /api/v1/auth/sessions/{id})
func (_ Unimplemented) DeleteMySession(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all registered projects
// (GET /api/v1/projects)
func (_ Unimplemented) ListProjects(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new project
// (POST /api/v1/projects)
func (_ Unimplemented) CreateProject(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a project (and all its indexed data)
// (DELETE /api/v1/projects/{path})
func (_ Unimplemented) DeleteProject(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get one project by hash
// (GET /api/v1/projects/{path})
func (_ Unimplemented) GetProject(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Patch project settings
// (PATCH /api/v1/projects/{path})
func (_ Unimplemented) UpdateProject(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Open an indexing session
// (POST /api/v1/projects/{path}/index/begin)
func (_ Unimplemented) IndexBegin(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cancel any active indexing session (idempotent)
// (POST /api/v1/projects/{path}/index/cancel)
func (_ Unimplemented) IndexCancel(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit a batch of files (max 50)
// (POST /api/v1/projects/{path}/index/files)
func (_ Unimplemented) IndexFiles(w http.ResponseWriter, r *http.Request, path ProjectHash, params IndexFilesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Commit the indexing session
// (POST /api/v1/projects/{path}/index/finish)
func (_ Unimplemented) IndexFinish(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Live progress of the current run, or last completed run
// (GET /api/v1/projects/{path}/index/status)
func (_ Unimplemented) IndexStatus(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Semantic (vector) search
// (POST /api/v1/projects/{path}/search)
func (_ Unimplemented) SemanticSearch(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Go-to-definition by symbol name
// (POST /api/v1/projects/{path}/search/definitions)
func (_ Unimplemented) SearchDefinitions(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// File-path substring search
// (POST /api/v1/projects/{path}/search/files)
func (_ Unimplemented) SearchFiles(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Find references to a symbol
// (POST /api/v1/projects/{path}/search/references)
func (_ Unimplemented) SearchReferences(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Symbol search by name (prefix/substring)
// (POST /api/v1/projects/{path}/search/symbols)
func (_ Unimplemented) SearchSymbols(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Project overview (top dirs, recent symbols, totals)
// (GET /api/v1/projects/{path}/summary)
func (_ Unimplemented) GetProjectSummary(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Server / sidecar status (authenticated)
// (GET /api/v1/status)
func (_ Unimplemented) GetStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe (public)
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListApiKeys operation middleware
func (siw *ServerInterfaceWrapper) ListApiKeys(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListApiKeysParams

	// ------------- Optional query parameter "owner" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "owner", r.URL.Query(), &params.Owner, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "owner"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApiKeys(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApiKey operation middleware
func (siw *ServerInterfaceWrapper) CreateApiKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApiKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeApiKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeApiKey(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBootstrapStatus operation middleware
func (siw *ServerInterfaceWrapper) GetBootstrapStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBootstrapStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangePassword operation middleware
func (siw *ServerInterfaceWrapper) ChangePassword(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangePassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMySessions operation middleware
func (siw *ServerInterfaceWrapper) ListMySessions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMySessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMySession operation middleware
func (siw *ServerInterfaceWrapper) DeleteMySession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMySession(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProject(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProject(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IndexBegin operation middleware
func (siw *ServerInterfaceWrapper) IndexBegin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IndexBegin(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IndexCancel operation middleware
func (siw *ServerInterfaceWrapper) IndexCancel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IndexCancel(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IndexFiles operation middleware
func (siw *ServerInterfaceWrapper) IndexFiles(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params IndexFilesParams

	headers := r.Header

	// ------------- Optional header parameter "Accept" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept")]; found {
		var Accept IndexFilesParamsAccept
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept", valueList[0], &Accept, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept", Err: err})
			return
		}

		params.Accept = &Accept

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IndexFiles(w, r, path, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IndexFinish operation middleware
func (siw *ServerInterfaceWrapper) IndexFinish(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IndexFinish(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IndexStatus operation middleware
func (siw *ServerInterfaceWrapper) IndexStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IndexStatus(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SemanticSearch operation middleware
func (siw *ServerInterfaceWrapper) SemanticSearch(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SemanticSearch(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchDefinitions operation middleware
func (siw *ServerInterfaceWrapper) SearchDefinitions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchDefinitions(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchFiles operation middleware
func (siw *ServerInterfaceWrapper) SearchFiles(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchFiles(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchReferences operation middleware
func (siw *ServerInterfaceWrapper) SearchReferences(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchReferences(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchSymbols operation middleware
func (siw *ServerInterfaceWrapper) SearchSymbols(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchSymbols(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProjectSummary operation middleware
func (siw *ServerInterfaceWrapper) GetProjectSummary(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProjectSummary(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/users", wrapper.CreateUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/admin/users/{id}", wrapper.DeleteUser)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/admin/users/{id}", wrapper.UpdateUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/api-keys", wrapper.ListApiKeys)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/api-keys", wrapper.CreateApiKey)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/api-keys/{id}", wrapper.RevokeApiKey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/bootstrap-status", wrapper.GetBootstrapStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/change-password", wrapper.ChangePassword)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/sessions", wrapper.ListMySessions)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/auth/sessions/{id}", wrapper.DeleteMySession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/projects", wrapper.ListProjects)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects", wrapper.CreateProject)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/projects/{path}", wrapper.DeleteProject)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/projects/{path}", wrapper.GetProject)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/projects/{path}", wrapper.UpdateProject)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/index/begin", wrapper.IndexBegin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/index/cancel", wrapper.IndexCancel)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/index/files", wrapper.IndexFiles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/index/finish", wrapper.IndexFinish)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/projects/{path}/index/status", wrapper.IndexStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/search", wrapper.SemanticSearch)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/search/definitions", wrapper.SearchDefinitions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/search/files", wrapper.SearchFiles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/search/references", wrapper.SearchReferences)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/search/symbols", wrapper.SearchSymbols)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/projects/{path}/summary", wrapper.GetProjectSummary)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/status", wrapper.GetStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H1rcxu5teBfOcXcqki6JCV7PMlEU/NBfszYO56xr2Rvdjc9qwa7D0lETaADoCXxulSVT/cH3MovzC/Z",
	"wgHQDxJNUraoSVL7TWJ343FwcN6PT4NMLkopUBg9OP00KJliCzSo6L/3Sv4ZM/Oa6bn9N0edKV4aLsXg",
	"dPA9V9rAk9/BHG8hmzOlQU4hvXh99uRgLrW5LJmZH6ZjuEBMRMqFQSVYcVy6QfXYDvuemXk6TsRgOOB2",
	"UPvNYDgQbIHNfwr/UnGF+eDUqAqHA53NccHsivCWLcrCvvr15Pf50+wP+IR9Nf3m5NnTwdB+baccnA7+",
	"75/YaHoy+sMvn5787u7fBsOBWZb2I20UF7PB3d2dnUSXUmikjb+QYlrwzNi/MykMCvqTlWXBM2YBcPxn",
	"baHwqbWYf1M4HZwOfnPcgPTYPdXHr5SSyk3UheI5almpDIEVClm+BLzl2mg4wPFsDLhgvADDrlAcDu6G",
	"g++lmvA8R7H/hZ1VZo7C2FExH8KkMlCw7EqDmSOEEwElC7QLeyNyvEX1UbBrxgs2sWey7xXSnFzMQKO6",
	"5hmCkAYyKaZ8VllsoWU5pHNj7H1FH8WcibzAnJaECtC9ORz8LM33shL5IyKUhcaU5rwbDj4KVpm5VPw/",
	"8RHW8BPX2h6MVMDFNSt4Dmfv38AVLt1aSiUz1Ppx0OQnVkylWlhkxb9UqA1MZL60a1v4ZdbYPOVY5Hpg",
	"x/DD2lnPSv4jLok6KlmiMtwRiUyhvRuXjFZu57B/DXJmcGT4AtfpzHDACfprPxdMm8tKbx5MVIW/WY4M",
	"bhiFl3aUe3xQsZ0+cHQ5sgF5I1DZodRlzxZLhVN+u85GXnJdFmw5kqJYgnvJ8hFLZaZVUVik8cQwzfjt",
	"JXsyeZp9lT9LD8eJeCvFDFDIajYHI0FhJmeCawQuoLBkdAh6LpWp35kzA9wkImPCXg/7gdBGVZmhCaXi",
	"My5Y4RjS2hYUXssrbG9vImWBTLQefsEB3rU53Z8sqqzC1R9ADcxhGweb9f1SDy0nltXa5TkkfuFeX8dl",
	"VvLLK4fkmy6Zvwp3w4E9m/BF90A/zBHKgll+f2vo+K5ZUeEYjo7O0VRKYA54yzJTLEGKDMdHR3BhpEI6",
	"GY1ZpbBYwt//+jd7JvZnDULCDVu6MzaK47V9GQpmUEXPagWUYXetZffD6C3X5twLA72Aor+5wYXeHWR+",
	"PqYUc/9Lw4oWMlmIzVD1rV4PwiextT+X0mijWHlhmKl0/wYEYq4vJ+H1yPmpCuFmjoKuhEU9DcairT0I",
	"XJRmOW4AXl+AlTWvzhJb8os5EzN8z7S+kSo/d8Q5QmYrpVBYcdK9aH9bcPEWxczMB6dPYmQKbzqvr3In",
	"wRfVAr4hqZVlVtodw88SqrJEBRPLM+0WW5N8sw3D1ha5sojo/ukyOvzo3X2guN0tvK4WTIymiqPIiyUU",
	"bIKFJXU3wpI+e2450/OJZCofw4cWKU0EXUZ7lDMUqCw18MLKSPMcgQnLJ2PXlO7ZRsCv4oBdev/GvXLR",
	"u/Nah4iwk5WZmlf7p/uoUfXORXJ2h267X2IcXHDDWbEBv94JR/EhvEIHIvCGLhMsKm0s5okZghQwJTWq",
	"kDMuxomwZ8XyBReg50yhlba5BlmZkZyOJkzka8fwTYxRSSdYoagWREHsiIPh4JrjDaoWkHrgGTa/tlc/",
	"dAzKL3FKr0vxxuAiAmKRXxZcYIzgDQdTXmDfYQ8HV1z0yU1iVrFZXCbpn61XjCkZ3eLe55rPBDOVwu04",
	"6Tk1Lb29P7+uYQOQ1jY2A7YXfT8XenzBjcPfKasKMzh9ckK4Zcnj4PRkGAGdXi4msthKg1eA4b/atr0+",
	"nqVQV4XZneeu4OIm3rtptyubCKvYxIZfcvVKGLXsOaNMVk7P2Qzk3aieR6fWwLEV1apvdzk5Gk/yNk/i",
	"34uN/D0v8Aclq/KcALM+xwS1udSZdNelJq3TQpK46gcU1WKyCxHYeNcXzGRz3B1D7Np/st+sI8cKANo3",
	"t7WhZso+0Ljh18WZeSWuLt0XkY20dOG1Z5tJqEBtNYE5v8dF+Zm+ec1N7I7c4+S0YcpsWJu7/310dZVY",
	"NIN1qGQATVjZsA3LvlN4z5aFZBGNpwXoFSPOh+9H34BVXsbwnAumlmBxQFv5qipysqtMEHQ1WXBjMB/H",
	"pAQ/+uU8ajq9eH02evq1s5zmfIbakOnUf5RGR9yI/r2XRvP/xHuSOY/rDbQ7e/FD9oHbkYK4BLD79V6x",
	"EKDBzMqp4ZUhSAVWmQY+hUrk/vn43ip2hytv4sF2axfIVDbv5cHrzPTpVmb6lwpVRIO+qCZuweBoTA5s",
	"xrjQBtJ6xen4ntK4m2vb5h6KA6/gwiNy4NfICrNxJ8zbFVeAjgbIBkWqb6pJjU6topRWYk6DLuM3073a",
	"lrfl1WA4qL/aLm/7EWLbISP3c5zxDdJfVRQdxJuyQuOqGfSPpNHbSwE3vETtHA0WybxDBuwqECY4lQpB",
	"lijsQ6u6aNSaS9Gj9m9ccu8pVKLPUKiNVJaPMe0ZOstzkuVY8b4zxtqXq3bfEqZKLoh6g70z8Pf/+m8I",
	"tFdOwSvtxXLk5gRP6cbwalGaZSJqK0gA0ZxpEHiNCiaIVtfO8RZzOJAKUnsMRHVSuGGalD/MDzvmqQCj",
	"VbR2wFjdei86vGAiw6IfuBk9L+KWylXDRf1u73T2LuuNusf96EJgySS23b5xn319sk4iGiS5D6GroelW",
	"tm1bvUC0soW+zBqL6WZaTrNdsizD8h7ve08I5pefQw9X5hyuLrpvlg0wEVz387gcC7Qypr1M3TNfu4uf",
	"eZaesl+6dedcZ/Ia1XZ4xnFg6z4f9vBrMG//YJ1n2MtC0N2ZXaxPu4YAvQB4r+RModavrqMy8DuBgPZR",
	"MCf+/PJ/XLz7GbRRyBaATvKFyRLS9+8uPsAxUcJjWk9KHDQR9rOs4HYQjSLXkJ4Rop5C28l3OxL5n7UU",
	"qbNTpjRr6jxxibAIoPiCC2bQeZ6vmeJMmG9Bmjkq77EDphBKWVYF2TOZBoUFXjNhHPldUUutUHUZJOP1",
	"s3Ew3PSsjRjr7+Bigvmluxe16sSF+d2zQQwVMBxBwASS8UgJqq/wJc3b/EtT5M3/uSQNyT0jhX84mCNT",
	"ZoKksLkt+7fcC79E7t6UdT0SLfcWDU2n3G/A65K/e5C89VcXqPW9lZ0NQoXRu/poV02hdDpb79EbMZXr",
	"1yg8hdKxPIfjLDP8GkdeqgoYDRlTilu57BpJ5cQi/9bdojm3ggHPWDGasqKYsOyq/opE1vBpugLhdJgI",
	"/xvBOh2SfT/tYnEauyT3pYBYsNKeqcZMinwF2rKyKlmPxec+ZP4zKG1r+zsY3uZMdyznCjPk1xYxhhsp",
	"9Abku9uGO/1sqPRvbJOq1lGxw2K6SJnyvMCU/KtCBtmesA6OocavqonkGVP0lou1cd+Fjxwm2+c1bNLj",
	"tBYp0+N0yrj7Q1VC1N8XTJuRqgS4NTox3c1xqSqhPUaGQ7ALJm+EW0PnKIYtCdYSMO7+8NN9ker1Vm7S",
	"uu7hMtrZc9njhtnoRfSr7EOhSqPahj4fdUSEog9jE/6EG7zjlZlfLtDMZcQv9gGLQnedk1ZUID5uJOhK",
	"TVmGkAwKOZOVSQZw4BHtEKRKxJzn5PY/8A5xsNxG6yZS4LcahDRzUlslFHIGsjIgp4dddPKDDoZ1XEDs",
	"Pn8Z4IYdUMTA2Jhe72si3mwG/oez2jabCYuLgcN7g+N2WsYFqtp0uMJjrWLPBTmvSeQM78OBnBoUgH+p",
	"WGERoglKjZtsPyOcq+OjXomfnGhZVAad8XipDS6cEUI6idrukRmpfqthwbI5F7jR7HtPdYsiu7x54oti",
	"yjQaw8VsKwvy53cRXvcMaOfv6N24YlQrsy0G4Le2UZqtyvyeB9obVjBcRcP2wbSAFDY9bHS0ToRWa0nr",
	"Z7ThWmyOSQoR1TtbYcJleyCzbD3/JrvsKoKsM9TbrKhysm4bVOKeCL9gt5dOcbq/x2Nt5tXhNu0nIHl3",
	"M+FYa+vYZrnTGT0axXOXt+81tCPl+p6AaU80XNnTyqJXJ9oEsmqxYDEX+aaIn8+mhFaCF6YNgJ2uyAW9",
	"73z5Md9oTaYiBqzyMucKM6uz3cM0WocO9N3Kfzz8aBPImuC1CWMXgTYizDrg1s4uhlPnOEWFIsO4z7Er",
	"SjVanf8oyjd6PcNnxQ1b+hhIrwchoMhLyYWB1rtRTt4W2+LjBkElbWSpFA4UTkMAJvkHNBh5hUIPyROt",
	"mJihbks0O0dVbfQoP6hs2PazbvfudyXG1jxbnLQ1KnxmnNS6B/frxw+Ham3ioXyx3SvyiK7YC1wwYXi2",
	"xXPu2W/EVPG8YNlVwbWh25YrWYKfF27mUnuvng/EASaaBAIFOjjR7dW4j+D8efJ2NJRu1SF5S3HHTgED",
	"OYXv37x9BTMlq1LDAWUvEW089IHulRLey78BAxdcNDFW8UDnTGouEDRf8IIpbpZjeLfgBqYWTC5RyS8b",
	"Dk7Gz+zviXghczxn4urVYoL56D++ORzDBYoc0pMU8LYseMZNQSH5OadMHpeyUUjpQ/K365+1G2nVU80N",
	"1qd+hVg6K+e+j76OxniYsIpV7O+7zjTCpVVIvM9gBRqsKEZZIbMroDcp60FkyyEoWYkcc3sETyDHjC9Y",
	"AWXBMtIkd7C+fk5QRzvgb0+kZLgCkjhwnQ3nQZKy8LbkCvVDJHJxfemjCnoSK+yda8VUkOl+6QItuA4Z",
	"arFIC68vakRxr4U2X90nKYw+2CkpLJa11NF5W9Bd2UMHXBtOebP26yF5D9He484XpOTUc25kf1sycZz1",
	"/DJYNS7/LCeR+/+iDlLxNu2OoRyUvNHbmQQr+eU1qnBlmrTp6ycxnJmw7ApFxIT73D0AnqMwfMpRhdy8",
	"mUzjZjXnqrT7W8gci1guy2xmt/U9yxDoHeB5GJbdWGageY7Hqwzp8mT0ww8fv++Zlga6LCTLMY+xGG92",
	"niMUBVuwkeeDdqaMKVBYSmXshWT5Em64mXMBX5+cwEKPE/E9K3QrRyp8xDWQdOtTX+dMQ6aYnmPeiQJq",
	"Xem25WaFWFi0AoUzrg0qzKFOm9962G4r7fPeLWRt97iDgB9rc3UxbeUU1nFh2DYdRa9D9F61VPMHS4XY",
	"pAvtpuRsSPjYpLW43WyKm/3/mTOfmTnjQLtF+7DTfLGwf49Q3wcSLjtbeyhNcQ0XH1FZ/Eim8W1JgZ/t",
	"jrjrnXJjYqDXbeIsJMTThjxZyJgAIaGQYoYKWKuCxhjOcVppzJ1yRXyHaQMoaHif80ccRaOxIr0duo9t",
	"hPy+7op+xhuqx1HLmHZNnYkhPq8PdPUTpy5LcMUHv0sK4TqAvQ/1y0X0/nNo0pXT8NIlMxS4rdGM4aX/",
	"0Wcyu8z/RLQPB645a5I1352HYhV94G/N8/mOtfuknMZJ+KLS5tIlknayUfvxZefDfADnGXcM322JFtCz",
	"4k0usvrYf+nBrs2qwYYAM8KGnQmjc/RvyRRzQ/bTOBLNskpxs7yw44YkOaZQnVVRH7LDQx9LDkxDeubL",
	"uFD05Ck8p68hqU5OvspevPlfl2fv31z++Op/0w+YDnwhE8IHerU5t7kxpauXwqPBa68/fHhPNyEQjjTj",
	"t15OTkF76wZkMscRCW2QM1xIMU6Ey2O+4Ypo0YIZexsnS4Mj7QzZLFNS62B88vKi/tZN0xIh00RQIBxw",
	"AekxK/nx9ZPjkJpheHalKQa/RJGTjuQjibpSaQhIZWDl1humcj3iwp4yM9yuxidjF0zkmlb/m99Aq/wR",
	"l4K2dCOhZIoVBRZE28kEpWlQpwawBXrNyCydJnNqPxzB0dFzq6dZ+nPcBL8cHZ2G8Fm/MzvqMaWCp6Rz",
	"+PpP/54IaOgT17oikxe8NqZ8R/F/Ul5xd0CXXjX18bT+CRFDYew4rDJywezGCsrsJ2uZZX/C0A5GrghK",
	"MEXoMXh9WVvmUtghplJZKMKTZ5CzpQ/fqllLsGG4jb94+waO4eLlj7TbTdjrg3E85tozU86maG/ADdN2",
	"Ztp7O+44AK7koytc6nQMP+LSxQNT6ZSRzmRpr47IiTtP0A7jC6VY3OHXPK8IFBbgsjLAplPMnA5HOqKL",
	"YXaI8b6aFDyrfT5ktXW4EAjB4SmkP7z6AMcu+Scd+n9zmWkKx6T/ZImClXy8ZIuifqWNBHXljJHHdvtp",
	"H67YIyI5B1IiAR8/vL58+ebi7PnbVy+/cxkp+oqXFHuViGyO2RX4kL9l4786yPEaC1kuMISV/v2vfwMG",
	"N0yR2YFrKORs5nJaEvHHWvv1mrPVfLVDWya8k6xTPcQEIOlE0EKfv3v34eLD+dn7y7OXP735+fLVT2dv",
	"3qbw7xB9+v7s4uKP785fphQshpg7McrVT3Dy08FUqsxZRP2drm9Nt9LC4RjOoMAZy5Z+LZ5upiQFSQEM",
	"pgr1HHJm2IRpukJ8UUrlA8wZaC5mBSYiRXE9qs8rDcID4R+hKlUdogUG4uKlU2B5rpBqUBFy+V/T2q2a",
	"utI5OgQ1gS4oNcgN6YsYTRBCODhYWe7j+VvQOLPHqCGzIkCxHIKWwYIQrkSDxIZdITBIP9k571L4eP42",
	"EXUlQF81yUXuHR1Ndyv7d3Q0TsQLuSgrQ0dPeLGlCCDB5oJSDAjhvCXAPujifvj62K24m30wl0JWyi3X",
	"pxykMEeWozpNhEaR003ZmIwA+oY7z4KrducEDItXLBECb6z2OcqRFEHMQ1qEhcN6dkUKTgDQQ385EpHW",
	"sfmpT7Nwd/HJCfj46TG8K/JAetwJ2JVb7cItPBFuSy73bLVsWnoIM3Q1rRyWe2wdURZH2E8AOZUI0Paf",
	"s6JwNevqd7S9ww17o9Jpes5KPIX0U+LLAySDU0gGjoz7yH1HxpPBnT3YDkUMqEQkBm/tZrgUIYoT6rTJ",
	"OsS9yf8rlomoY90/JT6X080+Ho/9bFbE4YbMm43EYq+llXiDUWxw/YTqljlCPDgdfDU+GX81aDmlakJr",
	"b+5xLS/OkCRiF77HpXiTD04HVgz96MW/TiHJpycnD1bhbk3ejVUgtGpowTUJyM9OnvSNWS/yuFMZkD76",
	"avtHTR1KkmpDQA/BAVhReMJ/4MiyPelDeyrMKu5B/fjlbjgopTbxCmK+CA4aknTS1Uo0KXF0XyOHm5UK",
	"OR/a9Xa4hmnBLOOCNKaAeA5px7vhRUEiwhof4Wa9Vs9guIIFTaEhX7QUtXku8+WDYcB6JaO7rhJit3K3",
	"hoJPHhQFY2gX6so9FtLZL/6w/Yu6jKv94OnTXdbVLk3Zxe034pobyydrzNqC3nfDGA05/sTzuyaZMuLw",
	"YTpjOYX51Fac3+rgMNSEqF7G0MG6Qy+7AfuMSzGEfUlf1AjbQZpnsUIMLufiMU/52fYv6tqq3fNyqwW2",
	"01kNO5WP//QpVo2YLBr9tYhXzSG/EC/JImp958wW0iBI1YmiiJgGfR6mCySPnWVjzNwT8Vm3lu5EfE72",
	"Tnzcwv6B0fIBiI+rlejMuw2y5MTZ7kOHvJ68UZBxFQn1YO1OrOSRsaJw6Vw0ERVwHfqwpZDFaPWgVcw9",
	"E0uXo4OFRhJfK6HRHNafUhYHKwoie0TlmvrgziNSX0nS8QediuDBxFkUMSP1L3vEz0j50Ai2/ojLX1tA",
	"WyxrBkLwZ642pAY+dWfZwaKAMv3y2nnr4I6O6tqvR0euKMblFS7TTi3JgBMtReRDJy1Mz+WNrtVGBpks",
	"lzCpjLGauciBQTKggJmWLpEIKrq4lJWT4zSiC6ohHToZBEPGGC4ai5dClmv/ucM/pze6YLK0X8rzZV33",
	"Ked1K4M+sqTXrRfcg8fZl4p9XyyTaV0FkSxUGI+iboQGbhXELEoSgSHLobMZWuzgyv7s5a8z4Rl06x0m",
	"lom4wqWVzq7llTeelagWzG6uVnWVvAFtmL14Du2coWzB1BXmiXAmk6audAraSYSsyrkBoxgvaGCFpOO6",
	"Kv2JaBl0vYGVLJTMGFyUwUTnaikUFcLUDkO/PTt5EkN42kSD8PsQlLbLnue+tvU/h+x5HhBhd6yMWX1b",
	"bDpOcdNPyWqp5WRwSr7ju3RLEedVmqtQ5PY1Jii+lwlmpFqCzpQrdRSMjpZpJwOmr5w5OeQxOmm2LKSz",
	"pEPMhHsEKK7hmtEsuaW4ZDVOBodUf5l1fC61ST2Gkz+gWal4vU/LS19x7QhZrF/1ue0dt9/g9E+/tNGk",
	"HYbWHAQdqLM1UJJ8fbRwUJL/ocOeKzOPYJIzW4zabuE47/6fqPiU7GmrJazTIThfLCkqabucdTokw7LS",
	"iYiaVHydCUe6gizovCkh7pVK/HOdCKedmcZX1YqIDa65eh91CwduJcPSJIIV/BoPx/BSooaf330AI6ts",
	"3sg3jtZKjeQTijl+ojy+U5p8X1w+Wv98Jz7/LJYH7UFUfak69EC6Ch2fw6lgw2j5/LfgL9nY+rH2nQBd",
	"Ufb/0NkI0ws0oxeEQKfQcoN+54zSPHf26G9rn+m3ibhgC7zgBr+7MIpn5lt4z8z8u+PUsu1GoCX89PVb",
	"oCwqTQb8KNY7bcxi3E03OKi522RYpCFWMdvTWV9+j4lwYVhGGWURJKXKD3vCzU7ti0fW87sVLSI09i25",
	"IYE277wgtIYGBWLVHX24vaMxBwENhrCCBYeDTaLK3WNfqh7G8erW26V9gEDj55xafa7JLvDb3ZlvuNIb",
	"/RfPGdV0y/Hr2gaECa1Ia0k/921V3JsTF/0ARiaCGEc3VIHir3pv8LfwE7sdnc3wu5O05xrYJe9CIwMW",
	"WEnncwlkh9S9EnmHzjWlRbbA2UXJbpTtauLDjGFUBdYbhF2gdA3yTrzaG+Fy6aCHQnkNoiFIV8Jq2k0Z",
	"lkTMmEGYVop+EOyaz5w4NsE5J9U7Trl6pLSfcJ+CWasWTcwr0eI+D3HaYbx27KCLK9x+4O0slY3H7oQl",
	"IcXIJc7kXZEpmMaGVudFbUYkJzrXciLSdn5NOoS0nf0Tqn+1E3xqjAjxq4nQpTRQiSlb8IIz5dxd2pfn",
	"axJ2PLezyqpuZzQ5D+16SlPs5nJtflpeNLk0e8OTWCJRBGECffgC+1wHYc46N1XXJ9jGy50xJ2KviHlz",
	"aoD+aqr6Q1DZL1O/LVmWAi28F8sG/AeazwTVhArRO5DjNc9wM2NsJ+n0Gs3fN4kse8PiWDGYCBaHOKIv",
	"sjJ/7da9+aNue8WeUIBIDlML3PVPbfNyzOAaatbs0+K6kn3wyCbXuipP/5F+scHVec333Dm0LpftLY1c",
	"d2Laup1OP1c6fgAUPfeY6Q3IZY1hEeSM0AMffbadJLdRd0cfOwWWTmS+PHwsAvoA8Kw97uH8D8hXUxTA",
	"ja6LpefMsMM+ChClrz+g6QXhySNev3+io/iBolibwvWTJfj2HXHC2xUUYvM2rxy320J3whxiEQn7pdvR",
	"rLFHtldsQBwfmlCTlkdDoF+Jor63mNA0lGjK4t2Lovp43gkGG+CXYedGnzWD1FXudRGAVjxfsHJTdwhw",
	"7RkScZB2+jWkh0GX8lXPMyYg8xHQDHIsDBvDe6Z1u1dEIoykhhzxNhwhBnoM9toA1yBLFwsbU6iazht7",
	"um7r3Uju1punP+TdivQS2aC3yRLF46kcjyVOiRoLalMA17UU5a1BLkmLvMENqXk0ImC/+mqXr9a6xHfp",
	"x7sSBbD1DbcoSF0EdAcK4kpD75uEpJ+Spgh1y/3Kpy1L7A3TcMXtG0NIqUGPfSERwnJp+9DX0oYLNqVE",
	"g4zCqEUmRRP9Tr4FSualtBKEF2/f/FYngryoFbkci6aw/KxiKu8lE66JzGDfd3elV03MSudAF3y+obLQ",
	"P4mg5VZP/hp/E9cu6wHPcVFKC9DDz0TkupbjPvD4grpzMKAmEZbz+YZJ5PLSMMFCipkvqu0rF4uaa44T",
	"EeqafX3iG+WVZEosCsovOTpqMnoEzqThdNJHR6cuo2VLIo6RiXBF+H2cz2el3iTiQNYtTUpKkRA49O48",
	"WEnH8Yk4h2P4o08JNHPWTbhxoTmxlfvsm07aEPeZd5FUnHS9FVHa9F9mU+OjA+hsEhHq3uvea/29r7W5",
	"JXRzS9KTtJSLIIt5vQ8PxCicA0wPx/DSFcU4jWQltQI5HTAbQ6SDZTyUc5UCDQex9feGe+5JDOq0xXpk",
	"lSPSwOrurgcsTb0nV0GDjpX+qolYt7tP5KpYukXRYoPTwafENUVJBqdJp1dNMhgmvg0GPVOjJ/STJWT0",
	"w4JxMZ5J+rHpJ5MMTp8Mk1ZXnmRw+vTkLhHrE/kuOP2juvqJdsSn0QFCouROIwyTupVPMjj9+ll8TbkU",
	"+FkLqokOvWg0/fj05OnvRifPRk9//+HJ70+ffn16cvJ/ksHqp007nxqWTe8dAl89dejgkgxOv3r2+/rl",
	"lSY89umJ3Z/jbrvjYLePVIS7v+IuiiEY3B2iOcyDA19A5xCc17qm5Q4hE0Fb1nBQR7J51UrajQIXznO8",
	"kYNQ84cvlCf2K+AH466QBqZWMIF35+DuUeu341pBXHC9CK2LfwURf7/A8CpCneFAvV5/eP+xLrI2qfRy",
	"DJR9bv8cQnqORi1HZ5ZXpjWXduVfQvy4rmYz6rcBN4wbOPBZtr4xSCuGpDVWdzNrFY7uunLgBbUDXpWi",
	"NBws2C18ffL5gp/groPww0h+UYmBptgrp2x3Ffx1WGWn398GE0ImF6653T8vzajElZA34h+HYnyhUeAF",
	"HQmR/weyC2yJribiwjrGFlLtTusUpQXPKTQ3NOgK4RfUPywdhkZsTWOz45rhHodObKtd2IaJSFe6qIWI",
	"jaBrObLX6trVLC0RU1YUoRqNU9QWksqxZJZjrhYNDZlaVOeE0l9Wm8f5hcY7xsGbabsxbiKoM670reqW",
	"wMj362oEOGiT4MLzApss/Qgx2n8sd7z1WvyKdZr3keJnN3D4q8Q0vLUacI1vK5EkqhLEKClxtG6OZn+O",
	"35Av8/hsuF+aKhLuy1JBpV9dtJGrhU1R5hUlRVvpT8lbvmAGQSBTqM1IIJ/NJ7JS4BaWiNBJvYW8v9WQ",
	"zZVc4GI0k5DJokAXcwvnvuI4U5gIu6TRlBculGGyhLQuvW5vM9WNSK2o6quXD31F8tG781FdkTwRRIgP",
	"h5CGsvcpHExCnfuhq7JB73AxO6wjtnxResq3pAxvAQtULgrWSKunjchq44vJE1yY1ZXsQieojRsTaLlk",
	"l2mtvi7mpU8TATAC6fu7/v2//nu1QHx6Mn6WwkHGCj5R5NuaSgVrxeLdOKFOPBWNt4P5FDsysrgkUDaR",
	"1wivf774o6sdv/JhKTUnq5r9mhJQ/FuJSDtVwqmsyIaK6BGC0y3QvicBKN4D4ZFloJ5S9DGi10EkCj70",
	"dd5CDc9/QRfmI6k2r0L1Y93Sbq6p3Y3r7GLlNKsmEylv6zuJOGgpJr6YkdVvtiowq0IuiRX2fpAeVKvV",
	"3i5CapOdMBYE36/6BBQ5cJs59MS2xXr8DxtFM/fOcY5TKvbiY2X3ofa4a/CyNdF+7n4zw69079sL6L/z",
	"P3luA23Q/6tHKvwgR0aOmh1bPuna8oCvP/0ZuPvAbpoY1gb7/j7w1Y79q/Kp9gJ2wFfvpzLzf310tZAZ",
	"UcubWpT8Iipbd0DT+/aOUz0b6dBB+6qeqbtpqZXZkbKBSYJvdZWgFmeusTThFYl3nP4MvnBXYZLk41AQ",
	"Hr77Dtq900hYLmVZFYzKY2rByxKNBlrFjayKPGQZA4NpVRQOpxSOFLLcitWUpFwV5tu6GJ+e03dTWRTy",
	"BqrS2RhrOckBGKiEHsud448Gda3t4vmmAenrQ9nPBV/rkPbI93u9uVnkereg8K9/qylLOuzX+11dc7jP",
	"utatNo77Y0EXdcfGvShMkaYNj60uxZorbGJEAez/6vjqABNI3GRJohIcODvHcc2ZDu+LvE1D2C3x36F1",
	"7P6jecNMMVdBePRPE6QUvAXyGtU1xxs4MLK0DEkPg33Yo/AQyOqrD/cRKd5CgR3rm3jj0wINy5lhp6FU",
	"/BAyKaZ8VinMoe4q5GquD0M2q6+EGGvvRHmJLJtTRZSDtN2mKD0cNh0aLfdfy15yRrmmi2O21qGrdlP8",
	"WU50T2Ls/i3d24uVuDeCgfshMh4vHJyPa0i7g4aDTs7sCnZN0NMHV/l3p6o3LaeCvEoG7Wo3/qxdQSaW",
	"zeHiP95yg6GL15NEOPdKU+fh65OvfEhXd+S6FrELbQnVhutiw76xgJ305XMoSSdhvNBj8IXi//7Xv4GQ",
	"K3XvQzXqbQVuXjto7BFD3Ayb3aIES25FZoLEQ1vL7rOEpjS06w738jlUor7HhxsrJrzl1yjIm2PxLVYR",
	"oUbE7ijdDh1/+sVKRw7DYpF1F60OChbn5ShHgxnZyUOXBFegXV3XKdK6RFpJpYrB6eCYBDC/qrWmHAQA",
	"V/zYX167bN0E0rlt3A0/9WaFTjFbZpbuvTj/+PKw86Wj8+sfO8Y/bFmIho3cOiSlyVHFFTWoGdz/vz70",
	"h7lCHJHjtKGbpZJGZiQFh0Tl4LxaH+Hs/RvIZVYtUBhCwearXGbR7fiM4KFLbvdVL4ZNFQ1X4mC4mqnt",
	"R6UU4cg66jKYLpt+wQSb4cI1tQ6fUk3O9W99Ibu6aFK3e0VdzYh8LW/fHF+8/NHO0Ro3FBW7++Xu/wUA",
	"AP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
