// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusOk        HealthResponseStatus = "ok"
	HealthResponseStatusUnhealthy HealthResponseStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case HealthResponseStatusOk:
		return true
	case HealthResponseStatusUnhealthy:
		return true
	default:
		return false
	}
}

// Defines values for IndexFinishResponseStatus.
const (
	IndexFinishResponseStatusCompleted IndexFinishResponseStatus = "completed"
)

// Valid indicates whether the value is a known member of the IndexFinishResponseStatus enum.
func (e IndexFinishResponseStatus) Valid() bool {
	switch e {
	case IndexFinishResponseStatusCompleted:
		return true
	default:
		return false
	}
}

// Defines values for IndexProgressEventEvent.
const (
	IndexProgressEventEventBatchDone    IndexProgressEventEvent = "batch_done"
	IndexProgressEventEventError        IndexProgressEventEvent = "error"
	IndexProgressEventEventFileChunked  IndexProgressEventEvent = "file_chunked"
	IndexProgressEventEventFileDone     IndexProgressEventEvent = "file_done"
	IndexProgressEventEventFileEmbedded IndexProgressEventEvent = "file_embedded"
	IndexProgressEventEventFileError    IndexProgressEventEvent = "file_error"
	IndexProgressEventEventFileStarted  IndexProgressEventEvent = "file_started"
	IndexProgressEventEventHeartbeat    IndexProgressEventEvent = "heartbeat"
)

// Valid indicates whether the value is a known member of the IndexProgressEventEvent enum.
func (e IndexProgressEventEvent) Valid() bool {
	switch e {
	case IndexProgressEventEventBatchDone:
		return true
	case IndexProgressEventEventError:
		return true
	case IndexProgressEventEventFileChunked:
		return true
	case IndexProgressEventEventFileDone:
		return true
	case IndexProgressEventEventFileEmbedded:
		return true
	case IndexProgressEventEventFileError:
		return true
	case IndexProgressEventEventFileStarted:
		return true
	case IndexProgressEventEventHeartbeat:
		return true
	default:
		return false
	}
}

// Defines values for IndexProgressInfoPhase.
const (
	IndexProgressInfoPhaseCompleted IndexProgressInfoPhase = "completed"
	IndexProgressInfoPhaseReceiving IndexProgressInfoPhase = "receiving"
)

// Valid indicates whether the value is a known member of the IndexProgressInfoPhase enum.
func (e IndexProgressInfoPhase) Valid() bool {
	switch e {
	case IndexProgressInfoPhaseCompleted:
		return true
	case IndexProgressInfoPhaseReceiving:
		return true
	default:
		return false
	}
}

// Defines values for IndexProgressResponseStatus.
const (
	Cancelled IndexProgressResponseStatus = "cancelled"
	Completed IndexProgressResponseStatus = "completed"
	Failed    IndexProgressResponseStatus = "failed"
	Idle      IndexProgressResponseStatus = "idle"
	Indexing  IndexProgressResponseStatus = "indexing"
	Running   IndexProgressResponseStatus = "running"
)

// Valid indicates whether the value is a known member of the IndexProgressResponseStatus enum.
func (e IndexProgressResponseStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Completed:
		return true
	case Failed:
		return true
	case Idle:
		return true
	case Indexing:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// Defines values for ProjectStatus.
const (
	ProjectStatusCreated  ProjectStatus = "created"
	ProjectStatusError    ProjectStatus = "error"
	ProjectStatusIndexed  ProjectStatus = "indexed"
	ProjectStatusIndexing ProjectStatus = "indexing"
)

// Valid indicates whether the value is a known member of the ProjectStatus enum.
func (e ProjectStatus) Valid() bool {
	switch e {
	case ProjectStatusCreated:
		return true
	case ProjectStatusError:
		return true
	case ProjectStatusIndexed:
		return true
	case ProjectStatusIndexing:
		return true
	default:
		return false
	}
}

// Defines values for ReferenceItemChunkType.
const (
	Reference ReferenceItemChunkType = "reference"
)

// Valid indicates whether the value is a known member of the ReferenceItemChunkType enum.
func (e ReferenceItemChunkType) Valid() bool {
	switch e {
	case Reference:
		return true
	default:
		return false
	}
}

// Defines values for StatusResponseStatus.
const (
	StatusResponseStatusOk StatusResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the StatusResponseStatus enum.
func (e StatusResponseStatus) Valid() bool {
	switch e {
	case StatusResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for IndexFilesParamsAccept.
const (
	Applicationjson    IndexFilesParamsAccept = "application/json"
	ApplicationxNdjson IndexFilesParamsAccept = "application/x-ndjson"
)

// Valid indicates whether the value is a known member of the IndexFilesParamsAccept enum.
func (e IndexFilesParamsAccept) Valid() bool {
	switch e {
	case Applicationjson:
		return true
	case ApplicationxNdjson:
		return true
	default:
		return false
	}
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	HostPath string `json:"host_path"`
}

// DefinitionItem defines model for DefinitionItem.
type DefinitionItem struct {
	EndLine    int     `json:"end_line"`
	FilePath   string  `json:"file_path"`
	Kind       string  `json:"kind"`
	Language   string  `json:"language"`
	Line       int     `json:"line"`
	Name       string  `json:"name"`
	ParentName *string `json:"parent_name,omitempty"`
	Signature  *string `json:"signature,omitempty"`
}

// DefinitionRequest defines model for DefinitionRequest.
type DefinitionRequest struct {
	FilePath *string `json:"file_path,omitempty"`
	Kind     *string `json:"kind,omitempty"`
	Limit    *int    `json:"limit,omitempty"`
	Symbol   string  `json:"symbol"`
}

// DefinitionResponse defines model for DefinitionResponse.
type DefinitionResponse struct {
	Results []DefinitionItem `json:"results"`
	Total   int              `json:"total"`
}

// DirEntry defines model for DirEntry.
type DirEntry struct {
	FileCount int    `json:"file_count"`
	Path      string `json:"path"`
}

// Error defines model for Error.
type Error struct {
	Detail string `json:"detail"`
}

// FileGroupResult defines model for FileGroupResult.
type FileGroupResult struct {
	BestScore float32     `json:"best_score"`
	FilePath  string      `json:"file_path"`
	Language  *string     `json:"language,omitempty"`
	Matches   []FileMatch `json:"matches"`
}

// FileMatch defines model for FileMatch.
type FileMatch struct {
	ChunkType  string       `json:"chunk_type"`
	Content    string       `json:"content"`
	EndLine    int          `json:"end_line"`
	NestedHits *[]NestedHit `json:"nested_hits,omitempty"`
	Score      float32      `json:"score"`
	StartLine  int          `json:"start_line"`
	SymbolName *string      `json:"symbol_name,omitempty"`
}

// FilePayload defines model for FilePayload.
type FilePayload struct {
	// Content UTF-8 text. Binary files should not be submitted.
	Content string `json:"content"`

	// ContentHash SHA-256 hex digest of `content`.
	ContentHash string  `json:"content_hash"`
	Language    *string `json:"language,omitempty"`
	Path        string  `json:"path"`
	Size        int     `json:"size"`
}

// FileResultItem defines model for FileResultItem.
type FileResultItem struct {
	FilePath string `json:"file_path"`

	// Language Detected language, or null if undetected.
	Language *string `json:"language"`
}

// FileSearchRequest defines model for FileSearchRequest.
type FileSearchRequest struct {
	Limit *int `json:"limit,omitempty"`

	// Query Substring matched against `file_path`.
	Query string `json:"query"`
}

// FileSearchResponse defines model for FileSearchResponse.
type FileSearchResponse struct {
	Results []FileResultItem `json:"results"`
	Total   int              `json:"total"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Reason Set only when `status` is `unhealthy`.
	Reason *string              `json:"reason,omitempty"`
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// IndexBeginRequest defines model for IndexBeginRequest.
type IndexBeginRequest struct {
	// Full When true, wipes existing project state before opening the session.
	Full *bool `json:"full,omitempty"`
}

// IndexBeginResponse defines model for IndexBeginResponse.
type IndexBeginResponse struct {
	RunId string `json:"run_id"`

	// StoredHashes Map from file path → SHA-256 of currently-stored content. Empty
	// when the project has never been indexed (or `full:true` was passed).
	StoredHashes map[string]string `json:"stored_hashes"`
}

// IndexCancelResponse defines model for IndexCancelResponse.
type IndexCancelResponse struct {
	Cancelled bool `json:"cancelled"`
}

// IndexFilesRequest defines model for IndexFilesRequest.
type IndexFilesRequest struct {
	Files []FilePayload `json:"files"`
	RunId string        `json:"run_id"`
}

// IndexFilesResponse defines model for IndexFilesResponse.
type IndexFilesResponse struct {
	ChunksCreated       int `json:"chunks_created"`
	FilesAccepted       int `json:"files_accepted"`
	FilesProcessedTotal int `json:"files_processed_total"`
}

// IndexFinishRequest defines model for IndexFinishRequest.
type IndexFinishRequest struct {
	DeletedPaths         *[]string `json:"deleted_paths,omitempty"`
	RunId                string    `json:"run_id"`
	TotalFilesDiscovered *int      `json:"total_files_discovered,omitempty"`
}

// IndexFinishResponse defines model for IndexFinishResponse.
type IndexFinishResponse struct {
	ChunksCreated  int                       `json:"chunks_created"`
	FilesProcessed int                       `json:"files_processed"`
	Status         IndexFinishResponseStatus `json:"status"`
}

// IndexFinishResponseStatus defines model for IndexFinishResponse.Status.
type IndexFinishResponseStatus string

// IndexProgressEvent One event in the NDJSON stream emitted by `POST /index/files` when
// the client sends `Accept: application/x-ndjson`. The `event` field
// discriminates the variant; other fields are populated as relevant.
type IndexProgressEvent struct {
	BatchSize           *int                    `json:"batch_size,omitempty"`
	Chunks              *int                    `json:"chunks,omitempty"`
	ChunksCreated       *int                    `json:"chunks_created,omitempty"`
	EmbedMs             *int64                  `json:"embed_ms,omitempty"`
	Event               IndexProgressEventEvent `json:"event"`
	Fatal               *bool                   `json:"fatal,omitempty"`
	FileIndex           *int                    `json:"file_index,omitempty"`
	FilesAccepted       *int                    `json:"files_accepted,omitempty"`
	FilesProcessedTotal *int                    `json:"files_processed_total,omitempty"`
	Message             *string                 `json:"message,omitempty"`
	Path                *string                 `json:"path,omitempty"`
	RunId               *string                 `json:"run_id,omitempty"`
	Ts                  *time.Time              `json:"ts,omitempty"`
}

// IndexProgressEventEvent defines model for IndexProgressEvent.Event.
type IndexProgressEventEvent string

// IndexProgressInfo Progress payload. The active-session variant carries every field;
// the historical-fallback variant only carries `files_processed`,
// `files_total`, and `chunks_created`.
type IndexProgressInfo struct {
	ChunksCreated   *int                    `json:"chunks_created,omitempty"`
	ElapsedSeconds  *float64                `json:"elapsed_seconds,omitempty"`
	FilesDiscovered *int                    `json:"files_discovered,omitempty"`
	FilesProcessed  *int                    `json:"files_processed,omitempty"`
	FilesTotal      *int                    `json:"files_total,omitempty"`
	Phase           *IndexProgressInfoPhase `json:"phase,omitempty"`
	RunId           *string                 `json:"run_id,omitempty"`
}

// IndexProgressInfoPhase defines model for IndexProgressInfo.Phase.
type IndexProgressInfoPhase string

// IndexProgressResponse defines model for IndexProgressResponse.
type IndexProgressResponse struct {
	// Progress Progress payload. The active-session variant carries every field;
	// the historical-fallback variant only carries `files_processed`,
	// `files_total`, and `chunks_created`.
	Progress *IndexProgressInfo `json:"progress,omitempty"`

	// Status `idle` — no session ever / fallback unavailable.
	// `indexing` — session active.
	// `completed`/`cancelled`/`failed`/`running` — last-run status from `index_runs`.
	Status IndexProgressResponseStatus `json:"status"`
}

// IndexProgressResponseStatus `idle` — no session ever / fallback unavailable.
// `indexing` — session active.
// `completed`/`cancelled`/`failed`/`running` — last-run status from `index_runs`.
type IndexProgressResponseStatus string

// NestedHit defines model for NestedHit.
type NestedHit struct {
	ChunkType  string  `json:"chunk_type"`
	EndLine    int     `json:"end_line"`
	Score      float32 `json:"score"`
	StartLine  int     `json:"start_line"`
	SymbolName *string `json:"symbol_name,omitempty"`
}

// Project defines model for Project.
type Project struct {
	// ContainerPath Path inside the container (often equal to host_path).
	ContainerPath string    `json:"container_path"`
	CreatedAt     time.Time `json:"created_at"`

	// HostPath Absolute filesystem path on the operator's machine.
	HostPath      string          `json:"host_path"`
	Languages     []string        `json:"languages"`
	LastIndexedAt *time.Time      `json:"last_indexed_at"`
	Settings      ProjectSettings `json:"settings"`
	Stats         ProjectStats    `json:"stats"`
	Status        ProjectStatus   `json:"status"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

// ProjectStatus defines model for Project.Status.
type ProjectStatus string

// ProjectListResponse defines model for ProjectListResponse.
type ProjectListResponse struct {
	Projects []Project `json:"projects"`
	Total    int       `json:"total"`
}

// ProjectSettings defines model for ProjectSettings.
type ProjectSettings struct {
	ExcludePatterns []string `json:"exclude_patterns"`
	MaxFileSize     int      `json:"max_file_size"`
}

// ProjectStats defines model for ProjectStats.
type ProjectStats struct {
	IndexedFiles int `json:"indexed_files"`
	TotalChunks  int `json:"total_chunks"`
	TotalFiles   int `json:"total_files"`
	TotalSymbols int `json:"total_symbols"`
}

// ProjectSummary defines model for ProjectSummary.
type ProjectSummary struct {
	HostPath       string        `json:"host_path"`
	Languages      []string      `json:"languages"`
	RecentSymbols  []SymbolEntry `json:"recent_symbols"`
	Status         string        `json:"status"`
	TopDirectories []DirEntry    `json:"top_directories"`
	TotalChunks    int           `json:"total_chunks"`
	TotalFiles     int           `json:"total_files"`
	TotalSymbols   int           `json:"total_symbols"`
}

// ReferenceItem defines model for ReferenceItem.
type ReferenceItem struct {
	ChunkType ReferenceItemChunkType `json:"chunk_type"`

	// Content Always empty — see endpoint description.
	Content string `json:"content"`

	// EndLine Always equal to `start_line` (refs table stores tokens, not ranges).
	EndLine    int    `json:"end_line"`
	FilePath   string `json:"file_path"`
	Language   string `json:"language"`
	StartLine  int    `json:"start_line"`
	SymbolName string `json:"symbol_name"`
}

// ReferenceItemChunkType defines model for ReferenceItem.ChunkType.
type ReferenceItemChunkType string

// ReferenceRequest defines model for ReferenceRequest.
type ReferenceRequest struct {
	FilePath *string `json:"file_path,omitempty"`
	Limit    *int    `json:"limit,omitempty"`
	Symbol   string  `json:"symbol"`
}

// ReferenceResponse defines model for ReferenceResponse.
type ReferenceResponse struct {
	Results []ReferenceItem `json:"results"`
	Total   int             `json:"total"`
}

// SemanticSearchRequest defines model for SemanticSearchRequest.
type SemanticSearchRequest struct {
	// Excludes Blacklist — drop results whose path matches any prefix or substring.
	Excludes  *[]string `json:"excludes,omitempty"`
	Languages *[]string `json:"languages,omitempty"`

	// Limit Maximum number of FILE groups (not chunks) to return.
	Limit *int `json:"limit,omitempty"`

	// MinScore Minimum cosine similarity. Omit for server default (0.4 for
	// CodeRankEmbed-Q8). Send `0` explicitly to disable the floor.
	MinScore *float32 `json:"min_score,omitempty"`

	// Paths Whitelist — keep only results whose path matches any prefix or substring.
	Paths *[]string `json:"paths,omitempty"`
	Query string    `json:"query"`
}

// SemanticSearchResponse defines model for SemanticSearchResponse.
type SemanticSearchResponse struct {
	// QueryTimeMs Wall-clock query latency, rounded to 1 decimal place.
	QueryTimeMs float64           `json:"query_time_ms"`
	Results     []FileGroupResult `json:"results"`
	Total       int               `json:"total"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	// ActiveIndexingJobs Currently-running `index_runs` rows.
	ActiveIndexingJobs int    `json:"active_indexing_jobs"`
	ApiVersion         string `json:"api_version"`

	// Backend Backend identifier (e.g. `go`).
	Backend string `json:"backend"`

	// EmbeddingModel Hugging Face model id (e.g. `awhiteside/CodeRankEmbed-Q8_0-GGUF`).
	EmbeddingModel string `json:"embedding_model"`

	// ModelLoaded Whether the llama-server sidecar reports ready within 500 ms.
	// False when the sidecar is starting or has crashed.
	ModelLoaded bool `json:"model_loaded"`

	// Projects Total registered projects.
	Projects      int                  `json:"projects"`
	ServerVersion string               `json:"server_version"`
	Status        StatusResponseStatus `json:"status"`
}

// StatusResponseStatus defines model for StatusResponse.Status.
type StatusResponseStatus string

// SymbolEntry defines model for SymbolEntry.
type SymbolEntry struct {
	FilePath string `json:"file_path"`
	Kind     string `json:"kind"`
	Language string `json:"language"`
	Name     string `json:"name"`
}

// SymbolResultItem defines model for SymbolResultItem.
type SymbolResultItem struct {
	EndLine    int     `json:"end_line"`
	FilePath   string  `json:"file_path"`
	Kind       string  `json:"kind"`
	Language   string  `json:"language"`
	Line       int     `json:"line"`
	Name       string  `json:"name"`
	ParentName *string `json:"parent_name,omitempty"`
	Signature  *string `json:"signature,omitempty"`
}

// SymbolSearchRequest defines model for SymbolSearchRequest.
type SymbolSearchRequest struct {
	Kinds *[]string `json:"kinds,omitempty"`
	Limit *int      `json:"limit,omitempty"`
	Query string    `json:"query"`
}

// SymbolSearchResponse defines model for SymbolSearchResponse.
type SymbolSearchResponse struct {
	Results []SymbolResultItem `json:"results"`
	Total   int                `json:"total"`
}

// UpdateProjectRequest defines model for UpdateProjectRequest.
type UpdateProjectRequest struct {
	Settings *ProjectSettings `json:"settings,omitempty"`
}

// ProjectHash defines model for ProjectHash.
type ProjectHash = string

// IndexerUnavailable defines model for IndexerUnavailable.
type IndexerUnavailable = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unprocessable defines model for Unprocessable.
type Unprocessable = Error

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// IndexFilesParams defines parameters for IndexFiles.
type IndexFilesParams struct {
	// Accept `application/x-ndjson` switches to a streamed response
	// (one `IndexProgressEvent` per line). Default: `application/json`.
	Accept *IndexFilesParamsAccept `json:"Accept,omitempty"`
}

// IndexFilesParamsAccept defines parameters for IndexFiles.
type IndexFilesParamsAccept string

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProjectRequest

// IndexBeginJSONRequestBody defines body for IndexBegin for application/json ContentType.
type IndexBeginJSONRequestBody = IndexBeginRequest

// IndexFilesJSONRequestBody defines body for IndexFiles for application/json ContentType.
type IndexFilesJSONRequestBody = IndexFilesRequest

// IndexFinishJSONRequestBody defines body for IndexFinish for application/json ContentType.
type IndexFinishJSONRequestBody = IndexFinishRequest

// SemanticSearchJSONRequestBody defines body for SemanticSearch for application/json ContentType.
type SemanticSearchJSONRequestBody = SemanticSearchRequest

// SearchDefinitionsJSONRequestBody defines body for SearchDefinitions for application/json ContentType.
type SearchDefinitionsJSONRequestBody = DefinitionRequest

// SearchFilesJSONRequestBody defines body for SearchFiles for application/json ContentType.
type SearchFilesJSONRequestBody = FileSearchRequest

// SearchReferencesJSONRequestBody defines body for SearchReferences for application/json ContentType.
type SearchReferencesJSONRequestBody = ReferenceRequest

// SearchSymbolsJSONRequestBody defines body for SearchSymbols for application/json ContentType.
type SearchSymbolsJSONRequestBody = SymbolSearchRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all registered projects
	// (GET /api/v1/projects)
	ListProjects(w http.ResponseWriter, r *http.Request)
	// Register a new project
	// (POST /api/v1/projects)
	CreateProject(w http.ResponseWriter, r *http.Request)
	// Delete a project (and all its indexed data)
	// (DELETE /api/v1/projects/{path})
	DeleteProject(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Get one project by hash
	// (GET /api/v1/projects/{path})
	GetProject(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Patch project settings
	// (PATCH /api/v1/projects/{path})
	UpdateProject(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Open an indexing session
	// (POST /api/v1/projects/{path}/index/begin)
	IndexBegin(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Cancel any active indexing session (idempotent)
	// (POST /api/v1/projects/{path}/index/cancel)
	IndexCancel(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Submit a batch of files (max 50)
	// (POST /api/v1/projects/{path}/index/files)
	IndexFiles(w http.ResponseWriter, r *http.Request, path ProjectHash, params IndexFilesParams)
	// Commit the indexing session
	// (POST /api/v1/projects/{path}/index/finish)
	IndexFinish(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Live progress of the current run, or last completed run
	// (GET /api/v1/projects/{path}/index/status)
	IndexStatus(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Semantic (vector) search
	// (POST /api/v1/projects/{path}/search)
	SemanticSearch(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Go-to-definition by symbol name
	// (POST /api/v1/projects/{path}/search/definitions)
	SearchDefinitions(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// File-path substring search
	// (POST /api/v1/projects/{path}/search/files)
	SearchFiles(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Find references to a symbol
	// (POST /api/v1/projects/{path}/search/references)
	SearchReferences(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Symbol search by name (prefix/substring)
	// (POST /api/v1/projects/{path}/search/symbols)
	SearchSymbols(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Project overview (top dirs, recent symbols, totals)
	// (GET /api/v1/projects/{path}/summary)
	GetProjectSummary(w http.ResponseWriter, r *http.Request, path ProjectHash)
	// Server / sidecar status (authenticated)
	// (GET /api/v1/status)
	GetStatus(w http.ResponseWriter, r *http.Request)
	// Liveness probe (public)
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all registered projects
// (GET /api/v1/projects)
func (_ Unimplemented) ListProjects(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new project
// (POST /api/v1/projects)
func (_ Unimplemented) CreateProject(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a project (and all its indexed data)
// (DELETE /api/v1/projects/{path})
func (_ Unimplemented) DeleteProject(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get one project by hash
// (GET /api/v1/projects/{path})
func (_ Unimplemented) GetProject(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Patch project settings
// (PATCH /api/v1/projects/{path})
func (_ Unimplemented) UpdateProject(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Open an indexing session
// (POST /api/v1/projects/{path}/index/begin)
func (_ Unimplemented) IndexBegin(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cancel any active indexing session (idempotent)
// (POST /api/v1/projects/{path}/index/cancel)
func (_ Unimplemented) IndexCancel(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit a batch of files (max 50)
// (POST /api/v1/projects/{path}/index/files)
func (_ Unimplemented) IndexFiles(w http.ResponseWriter, r *http.Request, path ProjectHash, params IndexFilesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Commit the indexing session
// (POST /api/v1/projects/{path}/index/finish)
func (_ Unimplemented) IndexFinish(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Live progress of the current run, or last completed run
// (GET /api/v1/projects/{path}/index/status)
func (_ Unimplemented) IndexStatus(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Semantic (vector) search
// (POST /api/v1/projects/{path}/search)
func (_ Unimplemented) SemanticSearch(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Go-to-definition by symbol name
// (POST /api/v1/projects/{path}/search/definitions)
func (_ Unimplemented) SearchDefinitions(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// File-path substring search
// (POST /api/v1/projects/{path}/search/files)
func (_ Unimplemented) SearchFiles(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Find references to a symbol
// (POST /api/v1/projects/{path}/search/references)
func (_ Unimplemented) SearchReferences(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Symbol search by name (prefix/substring)
// (POST /api/v1/projects/{path}/search/symbols)
func (_ Unimplemented) SearchSymbols(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Project overview (top dirs, recent symbols, totals)
// (GET /api/v1/projects/{path}/summary)
func (_ Unimplemented) GetProjectSummary(w http.ResponseWriter, r *http.Request, path ProjectHash) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Server / sidecar status (authenticated)
// (GET /api/v1/status)
func (_ Unimplemented) GetStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe (public)
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProject(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProject(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IndexBegin operation middleware
func (siw *ServerInterfaceWrapper) IndexBegin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IndexBegin(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IndexCancel operation middleware
func (siw *ServerInterfaceWrapper) IndexCancel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IndexCancel(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IndexFiles operation middleware
func (siw *ServerInterfaceWrapper) IndexFiles(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params IndexFilesParams

	headers := r.Header

	// ------------- Optional header parameter "Accept" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept")]; found {
		var Accept IndexFilesParamsAccept
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept", valueList[0], &Accept, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept", Err: err})
			return
		}

		params.Accept = &Accept

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IndexFiles(w, r, path, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IndexFinish operation middleware
func (siw *ServerInterfaceWrapper) IndexFinish(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IndexFinish(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IndexStatus operation middleware
func (siw *ServerInterfaceWrapper) IndexStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IndexStatus(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SemanticSearch operation middleware
func (siw *ServerInterfaceWrapper) SemanticSearch(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SemanticSearch(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchDefinitions operation middleware
func (siw *ServerInterfaceWrapper) SearchDefinitions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchDefinitions(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchFiles operation middleware
func (siw *ServerInterfaceWrapper) SearchFiles(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchFiles(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchReferences operation middleware
func (siw *ServerInterfaceWrapper) SearchReferences(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchReferences(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchSymbols operation middleware
func (siw *ServerInterfaceWrapper) SearchSymbols(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchSymbols(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProjectSummary operation middleware
func (siw *ServerInterfaceWrapper) GetProjectSummary(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "path" -------------
	var path ProjectHash

	err = runtime.BindStyledParameterWithOptions("simple", "path", chi.URLParam(r, "path"), &path, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProjectSummary(w, r, path)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/projects", wrapper.ListProjects)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects", wrapper.CreateProject)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/projects/{path}", wrapper.DeleteProject)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/projects/{path}", wrapper.GetProject)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/projects/{path}", wrapper.UpdateProject)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/index/begin", wrapper.IndexBegin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/index/cancel", wrapper.IndexCancel)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/index/files", wrapper.IndexFiles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/index/finish", wrapper.IndexFinish)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/projects/{path}/index/status", wrapper.IndexStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/search", wrapper.SemanticSearch)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/search/definitions", wrapper.SearchDefinitions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/search/files", wrapper.SearchFiles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/search/references", wrapper.SearchReferences)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/projects/{path}/search/symbols", wrapper.SearchSymbols)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/projects/{path}/summary", wrapper.GetProjectSummary)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/status", wrapper.GetStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3rctvI1eCrnEJSFckFUpTHnkk4lR8e33edsWLZNbs78BJN4JDsEdCNdDckMS5V7a88QGqfME/yVZ9u",
	"XAmSkiwpmanvnwSgb6fP/cYvQSLzQgoURgfTL0HBFMvRoKL/TpT8BRPzhumV/TdFnSheGC5FMA1ecaUN",
	"HH8LK7yEZMWUBrmA+PTNs+ODldRmVjCzOozHcIoYiZgLg0qw7Khwk+qxnfaEmVU8jkQQBtxOascEYSBY",
	"js1/Cv9WcoVpMDWqxDDQyQpzZneElywvMvvp0/l36ePkT3jMvln8cfLkcRDa0XbJYBr835/ZaDEZ/enz",
	"l+Nvr34fhIFZF3aQNoqLZXB1dWUX0YUUGungb0WKl6g+CXbOeMbmdgkLKmFQGPsnK4qMJ8yC4ugXbeHx",
	"pbWt3ytcBNPgd0cNcI/cW330Uimp3JJdeNKaXCxBozrnCYKQBhIpFnxZ2sNfhcFbD0M3x73v6JNYMZFm",
	"mNKWUAG6L8PgR2leyVKk97+HD6hlqTw0FrTmVRh8Eqw0K6n43/EB9vAXrrW9GKmAi3OW8RSenbyFM1y7",
	"vRRKJqj1w6DJX1i2kCrHFCxZoDYwl+na7i3326zIBRYcs1QHdg4/rV31uUJm0JP2BzcHkb6SBSrDHQXU",
	"FGz/6ZNLmyR/bn36uaYsObezW/C8wAUX3G7+rcF8cyEU6SzjAlvrWFaxREK0Bc9w2zbC4Iw7FNx4kTGx",
	"LNkSh19uXc2xnYEhBVMozGzre82XgplS4X5o0Rx+6+3z+X2FDUBax9gN2K2XeFvo8Zwbx/AXrMxMMD2e",
	"hEHOBc/LPJhOwgHQ6XU+l5kdlHPxDsXSLnoc7gGGH7XveI4zb55PoS4zJ7i4wVzvI6oeLl7VyzKlGBGz",
	"kYZVp9h62t4hql1UowdPw9VLYdR6yx0lsnQMYzeQr0ePHp1aEw/tqJYh3e2kaBjP9i/ivxua+RXP8LWS",
	"ZfGBALO5xhy1melEOnKx3IyZYBosMslMI5xFmc+vwwR20nrOTLLC62OI3ftf7JhN5OgBoE25rQM1S24D",
	"jZt+AyjJqhRnMzdi4CAtobLxbjcLFagNprMVvwGh/Ehj3nAzRCM3uDltmDI79ubofxtf7TOLZrIOl6xA",
	"U+0sbMNy2y2csHUmWTpwDw2ge9rQx1ejP4LBSzOGH7hgag0WBzTolSyzlBSUOYIu5zk3BtPxpp5Z73W2",
	"GlSpT988Gz1+6jTqlC+tcLcqtR8UD864E/23Eo3mf8cbsjmP6w20O2fxU24Dt2MFwxrA9cm7C60XaDAx",
	"mEL1SWi1IFFmGfAFlCL17y3Y7FOnnzkTYjemdaTyLhlsj3aKTCWrrTJ4U5g+3itM/1aiExU99CjnbsPg",
	"eEwKbMm40AbieseEJDcRwW6tfYe7Kwncw4UHlMBvkGVm50mYV9B7QEcDUmRruFihgFgbZkodA9cQl2JF",
	"k66HKdN96nRce46fA3kWhEE9qrXN7RzPzjB0HLIWf8Al36H9lVnWQbwFyzT27Ymf7LGIKOCCF6gBL7k2",
	"Fsm8oQ52FwhzXEiFIAsU9qVZIWjUmkvROvxcygyZoIPs3PLWWyjFjA9rpdpIZeUY016gszQlXY5lJ505",
	"Nkb2DagCFkrmxL3B0gz86x//hIr3ygUkpbLqfrYeuTXBc7oxvMwLs44EoYKFQAWiFdMg0JrIc0QBnNwH",
	"KRxIBbG9BuI6MVwwDQXTGtND5/PowaiP1g4Y/aNvRYfnTCSYbQduQu8zbMO3fWPttZtvty5naVnvtD1u",
	"xhcqkUxq2+VbN+zpZJNFNEhyE0ZXQ9PtbN+xtgLR6hZ6lpAVne7X2Wm1GUsSLG7wvXcpYDq7DT/srRn2",
	"N71tlR0wEVxvl3EpZmh1TEtM3TvfoMVb3qXn7DO375TrRJ6j2g/PYRzYe867vfwazPsHbMoMSywE3WuL",
	"i81lNxBgKwBOlFwq1Prl+aAO/F4goH0F3DHAH1/8j9P3P4I2ClkO6DRfmK8hPnl/+hGOiBMe0X5ikqCR",
	"sMOSjNtJNIpUQ/yMEHUKbW/Z5Uikv2gp4jF8XCHEtGrsXFqRsAigeM4FM6hpI+dMcSbM9yDNCpV3fQFT",
	"CIUsysyeGpgGhRmeM2Ec++2ZpVapmlWa8ebdOBjuetdGjM1vMJ9jOnN0UZtOXJhvnwRDqIDVFVSYQDoe",
	"GUE1Cc9o3eZfWiJt/k8lWUjuHRn8YbBCpswcyWBzR/ZfuQ8+D9Degnke1Bcafmq65e0OvC77uwHL2/w0",
	"R61vbOzsUCpM9zZSZnBkOHnodtOau529dPRWLOQmGVVvoXAiz+E4Sww/x5HXqiqMhoQpxa1edo5kcmKW",
	"fu+oaMWtYsATlo0WLMvmLDmrR5HKWg2NexCOw0j4ZwTrOAQmUoi7WBwPEclNOSBmrLB3qjGRIu1BW5bW",
	"JNvi8bkJm78Fp20d/xqOtxVz4qCiRYUJ8nOLGOFODr0D+a724c52MVT4L/ZpVZuo2BExXaSMeZphDP/6",
	"f/8fhKx0e8I6OIIav8omJDamqJ4LWrlx1SCHyfZ9DZv4KK5VyvgoXjDu/lClEPX4jGkzUqUAt0enprs1",
	"ZqoU2mNkdQl2wxQ4dHvoXEXY0mAtA+PuD7/cV5lejXPspk683Y66/zi/WnOYanND4PCRpGFPGuMCVe3c",
	"6XFBa3pxoXmKJMLr7+FALgwKwL+VLAMjoQknDzvVHDOaMXNdZh5241vdfT2ba5mVBp17b60N5s5MlE7n",
	"sWdkRqo/aMhZsuICdzrmbqgQWxqYeQNy14n2eLTCQKOxZvxeJuHv77T63LOIa4+jb4dV19rcaJGoP9pO",
	"faMs0hte6NaQZNhHw/bFtIBUHTpstOgWWnW2tHlHO8jiHddmJyOnXIhr28kVsd2R46xef5fnrI8gmyHc",
	"yyQrU/I/GlTihgifs8uZU21v7pPeWLk/3a7zVEjePUx1rbX/Yrdm4MzSxjS4ztc3mtqxcn1DwLQXCntn",
	"6m26v9AukJV5zoaCmLuyBW7NCa2OJUwbANcikVP63kVbh6JXNZsacDEUs5QrTKxWfQPnVR3c3UaV/3n4",
	"0WaQNcNrM8YuAu1EmE3AbdzdEE59wAUqFAkOR4W6qlSjd/tBg3Jja+zuWXbB1howL8zaa6oIKNJCcmGg",
	"9e2gJG+rbcPzVopK3OhSMRwoXGgwVkgDeXA1GHmGQocUK1RMLFG3NZpr573sjPndqW7YjoTtj792NcbW",
	"OnvCaDUq3DKTZTPG9vThE1Zah7iraFmXRB4wWHaKOROGJ3tim178DhiTP2QsOcu4NkRtqZIF+HXhYiW1",
	"j7v4VAlgYg2FwgW/BKlAV2FOSxo3UZxvp28PJjv1Q0aXFrrgDDCQC3j19t1LWCpZFhoOKFGTeOOhZQIK",
	"TamEj8PuwMCciyYLpp9xSAMhkZoLBM1znjHFzXoM73NuYGHB5HIy/bbhYDJ+Yp9H4rlM8QMTZy/zOaaj",
	"v/7xcAynKFKIJzHgZZHxhJtsbXeackpaJKtmkUmpnH293/6sHf39WCI3WN/6GWLh/FD3ffV1vPxuAt99",
	"7N9GzjTDzBok3qvbgwbLslGSyeQM6EvImEGRrENQshQppvYKjiHFhOcsgyJjCVmS1/CP3Sbs3k7JuidW",
	"EvZAMghc0ja2A9X5jmaVxTj7Rc4HYPu8DtF6j07HTQRKXuj9BMgKPjtHpbmL+zfJ5OfHQ2rAnCVn6FIm",
	"e8zOvQCeojB8wVHBAY6XY4iXMh52WThHvT1fLlPMNud8Uy6X9livWIJA3wBPq2nZhSU0zVM86hP7bDJ6",
	"/frTqy3L0kSzTLIU0yHyRQqeWHaQZSxnI89j7EoJU6CwkMpoUMjSNVxws+ICnk4mkOtxJF6xTCPUsfFq",
	"ENdAmoPPoF4xDYlieoVpJwbeiim0reLuDj9aNAOFS64NKkyhLibYe9nuKO37vl7CxvWjbhV+bKzVxbTe",
	"LWziQtg2ywfJYZCuWmbPnSUC79Izr6dA7kh33qURutPsyhr777zxW+aNO9Du0ezsMl+tSN0g0e2OBHfn",
	"aHelhW/g4gMq4p/I7bivWOPWrt6roRQkjUlpdc1TO6rK2GYK1bNy0F3uSmF8YhMwDfEzX5xDofwp/ECj",
	"ISonk2+S52//1+zZydvZ/3z5v+kBxoEvTyEpQJ82UmFlTOGqYPhgJPXNx48nVIxjNWIrdeKEX3qxFYP2",
	"ihwkMsUR8VBIGeZSjCMRiY8rhAuuEJzGZSXVfG1wpJ3NzhIlta70bM++9fdumRZHjyNBUVngAuIjVvCj",
	"8+OjKk/Q8ORMU0JYgSIllcWHtbpCosqOYGDFyAVTqR5xYe+QGW53k6yYWCJkTKSadv+734GFs1U5XM6E",
	"ffiSgsS1ZwMvEywMxK9ffoQjl3YYh/7fVCa6CvzSA1mgYAUfr1mexZHwqKqBVRdI3gunuZPG1brKeAw/",
	"1YLfAayS+5hGwqoKwIR3wHQGAjegz3jh0jiSFSZncJDiOSk9h98Dc7OUBWRyGQnL4eCCKaGBzWVpwKx4",
	"DQ+P38DSVCEVQ9kX1dO4dnrFcM6yEnUVcgKdUWodmBUzkDDhc7mrdArgIhKfPrwDjcvcUhQkVlfJ1iFo",
	"WekgI53IAtMa+BoMO0NgEH+xa17F8OnDu0jUFZZuMe7O/ejR4nrllI8eja2FlxelQQs6guye4kqCzSml",
	"6Nh7q3QJ+8Kn6XikrUYfuR13s3dWUshSue36lJ0YVshSVNNIaBQpIcXOZB7QF9zZfXaWquTS2kEsEgIv",
	"7O2OUiRRgmmVVmThsJmdFIPjWTp0QGCRiOvcltinKbmkieMJ+PyDMbzPUp9+5K/b7hyEBLfxSLgjudzN",
	"fv1efAhLNE5BxiVL1mCRLMMRZUFV56lATiU22v7zLMtc8WT9jYZSO8NbsxxdDZ9esQKnEH+JfHlNFEwh",
	"Chzf9JkvjmdGwZW92A5dV6hEFrcjfC4FWeL2cZ12XKeINPmz2ToSda7Il8jnQrvVx+OxX81yZW7IQGqY",
	"rGW+QRjUarW1na7CwPOSYBp8M56MvwlaLoM+stlnSySp5iKrXIq3aTAN3nFtThpNuFOg+3gyubNSy6FI",
	"3UDhZcVGMq5JND+ZHG+bud7qUadQ9SoMnrp97x7ULfMlkVwFXggowLJBI8heELNaQCuw99lqoVIPgLdT",
	"B+qrrFGbH2S6vjPQDtaaXnUVIaNKvNq43uO7vt5dV1oFqm97q08mf7r/wt9ndbY5sTsr9zoijWXOLKf8",
	"fYrIP3n8+DpnaZcv3wWKfvCYCQwEXlS7HkbOqzDYInyavOJN1H1Bz9uo28GdJ0O1QpQWBAdCEq89/Iq7",
	"frJ/UF0ffxfwdHsHVt//gdXZLA/gRte1Bikz7HAbBxjkr6/RbAXh5AHJ71d0Fa+pGKip+5ivwVe/DTPe",
	"VjeNn4fXbT45anfbuPpMEtMVinavrWMS3hPfHjQ7r8W3HwRx3PZqwfdwCPRv4qgnFhOaeqwmZ+lGHNWr",
	"83NcctHv9XIL7PRKRb9dhynJNoPYJb7GZGBaBTRnxa7iKnDVTZE4iDvlTvGhtbFaRQMJE5B4A4hBiplh",
	"YzhhWrdLrSJhJNWzDVexVSbQGCzZWM1ZFk4Vdnpul+KawrV7IrfNYr6rzZ40d0lbA6V4A2R26tN5rTL/",
	"VdrRTansQdQpUWNBnbfMda1FOb+7dytx3WE1D8YE7KhvrjNqo1tRl3+8L1AA2zxwi4PUGZrX4CAus/q+",
	"WYg1ROscbmuLksCJgS+A1Td2wTSccftFCDHVt9oPIiEkuYl0lYoOp2xBfobE6k2lSKRojF+ykUvtCpcs",
	"p3n+7u0fdCQqx5M2LGvqMpYlU+lWNuFqMIP7pt1eqecAfrsvMlrBB+B/RYqW2z1lB3hK3CDWA55iXkgL",
	"0MNbInKdaHcfeHxKxW0MqMbKSj5fb0wVPxrmmElBIV4jq7RyUUvNcSSqpJOnE99nokBF6EvupUePGoee",
	"wKU0nG760aOpc2jt8cMZGQlXw4LOTLuV5y0SB7KuCLTbs7OEUGQlaQBdb5z3wx2O4SduVs51y7r+NufM",
	"HNq5d751vIbO3xWJAU9cvFnJG/u8HEyBLYyPctPdRKIqG9FbyfqVT4TsIUqvgmafz1OSN9tCltp3uY15",
	"IA7CuYLp4RheuKjadMAp2eqf54DZdNBzsAw6PfN8bHuDA4XB0P6HAuCf71EN6lSVP7DJMVD/fXW1BSxN",
	"wogLwdG10l81E+sWxw6QiuVbFIkIpsGXyNUURsE06pR6RkEY+SoyeqdGx/TIMjJ6kDMuxktJD5tyzCiY",
	"HodRq6g1CqaPJ1eR2FzIF5Fun9Ult9kZHw9OUMVJrjVDGNWVsFEwffpkeE+pFHirDdVMhz40mh4+njz+",
	"djR5Mnr83cfj76aPn04nk/8TBf2hTTVsDcumdJXAVy9dFUBGwfSbJ9/VH/dqWO3biT1fqwffjWr2XBn2",
	"gHR/ySlTh3muBw7RHObBgY/AH4JUNcexvNwhZCToyBoO6lwdb1pJe1DgAs452yNBqIHFV+oT96vgV87d",
	"unEkvP8Ajo5az45qAzHnOq86f/0bVPwHaC6Kqsr4TKlV0uuTT3WW1rzUax/DtX+GEH9Ao9ajZ1ZWxrWU",
	"5ho0eg80A10ul1QMCReMGzjwQTbf3MQNIe7Ymqt7mI0UiauuHnhK3bT6WpSGg5xdwtPJ7RU/wV0DrrvR",
	"/AY1BlriXiVluynHv0dUdtpl7HAhJDJ3vSF+vTyjFGdCXoj/HI7xlU6B53QlxP7vyC/Q5E/6eMNApynW",
	"cbaQaTf1mrmGnKdU/l3VtxOfiURM5fdxWPUxaPoCHNUC96hqZNBvYhBGIu41IaiyXipby7G9VtF7s7VI",
	"LFiWaUrKqQy1XGoDrsBpI+s49GehZFeRres+C/2NDjdcgLeLdl+pSFBjKek7PayBUezXpQg4aJPiwtMM",
	"myD9ADM6rXJU75cfbHQuGCaxTu8LMvzsAR4sJNeLp59jg2/Sgd/7qC3lk6DMmDZQ9xawj4cp5OsiPjvo",
	"S1NK4315Kih33CWPuEIFi5sWpYEJq/0peclzZhAEMoXajATy5WouSwVuY5GoGhG2kPcPGpKVkjnmo6WE",
	"RGYZJlRiBx98OQhTGAm7pdGCZy6VYb6GuK6LsdRMaSOxVVV9aUnoy0VG7z+M6nKRSBAjPgwhrmqSYjiY",
	"V0VIoUuyqTLXDj391xVD1H2CeqoIyFEtSQk20tppI/La+EofgguztpLd6By1cXMCbZf8Mq3d1+mHehoJ",
	"gBFI3x7pX//4Z796J56Mn8RwkLCMzxXFthZSwUYlj5unKuKhih47meM5zsliKDePzeU5wpsfT39yhT29",
	"gYXUnLxqdjRlQfmvIhF3Sjgoq2hHucoAw+lWz9yTAjRcoPbAOtCWOqEhptdBJGqo7zNTqyTg32AI84FM",
	"m5dV+YRuWTfnVIvsym6rxvjEytv2TiQOWoaJz2W09s1eA6av5JJaYemD7KDarPZ+ETKb7IIdP9xe06dC",
	"kQN3mEPPbFuixz/YqZq5b47SuvW5vi+zx5HBi9ZC90P7m43vH5juB1rTD/5Qg8+TboP+t56p8FqOjBw1",
	"J7Zy0tVMgy9guQXu3nGYZghrK//+feDrZpPoB8bXgUbOu/C17ov720dXC5kR1SPXquRXcdm6PYW+7+g4",
	"paBLhw7aShyFEDtKi63OjkxpYKTBt8pSqYLD9WVzLeWtZOL0ZxULdyUapB9XFWXw5z9Du7EFKcu+rSZB",
	"TPCiQKOBdnFB3fA9dgODRZllDqcUjhSy1KrVkXCKz/d1Lr7vor+QWSYvoCycj7HWkxyAgTLoWeoCfzSp",
	"6zuSrYdVUYf09aXcD4FvtK94YPre7Dwx+ENKNRR++1Rt7bT6vD7u6jp33IqsWz127k8EndbtdO7FYBqo",
	"+nxoc2moOnOXIKrA/lvHVweYisXN16QqwYHzcxzVkunwpsjbdOvak/9d9fW6/2zeaqWhUEH16leTpFRF",
	"C+Q5qnOOF3BgZGEFkg4r/7BH4RDI66sP7yNTvIUCezzwlfLgnU85GpYyw6ZVcWvY+r1BqNsSuPYToVUy",
	"zMqK7q39ITi1hkhWVD57ELf7HMSHYdM+x0r/jeol55RrWuwkGy0+6jDFL3I+mKrzGs39e7p7DUyGMNl1",
	"ry2a3zO4BUL3fAHK9eGtIO0b5B6wpgIY0x52zdHzB1f4txcrekEFeRYFV3Grn4fbQ8KEu2Q4/es7brBq",
	"A3IcCRdeGUM14dPJNz6lqztzXYroUluqYsO61rDVKP7FD1CQTcJ4psdwUs4znlQ9irt15lUxav37h1sw",
	"xP0QzH1iSO+nZgbDolWJdPVbMHfsLbvJFprKUNde5sUPUIqajg87PQGC6c+f++ETQdEci29wUNAFDSJi",
	"d5ZuT4GfP1vtyGHYUGbdKctxJBVfckE4L0fVjzu5YnqLKq4+W527X6fhGnSBtJNSZcE0OCIFzO9qo40A",
	"AYAYkKcs2rZu/RQtHeMq/LK1KnSByTqxfO/5h08vDjsjHZ/fHOwEf9jyEIWN3hqS0eS4Ys8Maib3/29O",
	"/XGlEEcUOG34ZqGkkQlpwX58HbzanOHZyVtIZVLmKAyhYDMqlYm2gue/AgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
