package tsgrammar

// Code generated by vendor.sh — DO NOT EDIT.
// Grammar: tree-sitter-grammars/tree-sitter-scss @ v1.0.0 (src)

// #cgo CFLAGS: -std=c11 -fPIC -I${SRCDIR}
// typedef struct TSLanguage TSLanguage;
// const TSLanguage *tree_sitter_scss(void);
import "C"
import "unsafe"

// Language returns the C TSLanguage pointer for scss.
func Language() unsafe.Pointer { return unsafe.Pointer(C.tree_sitter_scss()) }
