#!/usr/bin/env bash
# dashboard-inputs-hash.sh — print a deterministic digest of every input the
# dashboard build reads, so `make dashboard-build` can skip a rebuild that
# would produce identical output.
#
# Usage: dashboard-inputs-hash.sh <dashboard-dir> <openapi-spec>
#
# What is deliberately NOT hashed:
#   src/api/generated.ts — regenerated by `npm run gen:api` from the OpenAPI
#     spec on every build. Hashing it as well would mean the stamp written
#     before a spec bump never matches the tree that build produced, costing
#     one redundant rebuild each time.
#   devmock/ , devmock.html — local-only visual harness, gitignored, and not
#     an input of the production build (vite's entry is index.html alone).
#   node_modules/ — covered by package-lock.json, which is hashed.
#
# Paths are part of the digest (shasum prints them), so a rename invalidates
# the stamp even when file contents are untouched.
set -euo pipefail

DASHBOARD_DIR="${1:?dashboard dir required}"
OPENAPI_SPEC="${2:?openapi spec path required}"

hash_if_present() {
    [[ -f "$1" ]] && shasum -a 256 "$1"
    return 0
}

{
    find "$DASHBOARD_DIR/src" -type f \
        ! -path "$DASHBOARD_DIR/src/api/generated.ts" \
        -print0 | LC_ALL=C sort -z | xargs -0 shasum -a 256

    if [[ -d "$DASHBOARD_DIR/public" ]]; then
        find "$DASHBOARD_DIR/public" -type f -print0 |
            LC_ALL=C sort -z | xargs -0 shasum -a 256
    fi

    for f in index.html package.json package-lock.json vite.config.ts \
        tailwind.config.ts postcss.config.js tsconfig.json \
        tsconfig.node.json components.json; do
        hash_if_present "$DASHBOARD_DIR/$f"
    done

    hash_if_present "$OPENAPI_SPEC"
} | shasum -a 256 | awk '{print $1}'
