package tsgrammar

// Code generated by vendor.sh — DO NOT EDIT.
// Grammar: tree-sitter-grammars/tree-sitter-markdown @ v0.5.3 (tree-sitter-markdown/src)

// #cgo CFLAGS: -std=c11 -fPIC -I${SRCDIR}
// typedef struct TSLanguage TSLanguage;
// const TSLanguage *tree_sitter_markdown(void);
import "C"
import "unsafe"

// Language returns the C TSLanguage pointer for markdown.
func Language() unsafe.Pointer { return unsafe.Pointer(C.tree_sitter_markdown()) }
